### ISSUE TITLE
[BUG] Cython 3.0.0b1 miscompilation on `memoryview`

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [cython/cython#5268]
### Describe the bug

The example code blow produces a miscompilation on 3.0.0b1 while it used to work on 3.0.0a11. This is the relevant error:

```
      pytact/data_reader.c:2082:46: error: ‘None’ undeclared (first use in this function)
       2082 |     __pyx_t_4 = __Pyx_PyObject_LookupSpecial(None, __pyx_n_s_enter); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 2, __pyx_L3_error)
            |      
```

### Code to reproduce the behaviour:

```cython
def reader():
    with memoryview(b'abcefg') as mv:
        print(mv)
```

### Environment

OS: Arch linux
Python version 3.10.9
Cython version 3.0.0b1

**Comment by LasseBlaauwbroek** [comment]
Presumably this is related to https://github.com/cython/cython/pull/5073

**Comment by da-woods** [comment]
Thanks. Yes, probably related to the change you suggest.
