### ISSUE TITLE
[BUG] : regression in exceception types

### ISSUE THREAD

**Issue by tacaswell** [cython/cython#7902]
### Describe the bug

Running with the cython master branch I see compilation failures trying to build apache/arrow.  I bisected the failures back to

```
(cp315t) ~/s/p/c/cython 3.3.0a1-48-g43bf9d98e|BISECTING|✓
✔ 17:39:36 [belanna] @ git bisect good
95c0c67fe2083031c387cbdefb5853e5623dc96b is the first 'bad' commit
commit 95c0c67fe2083031c387cbdefb5853e5623dc96b
Author: Stefan Behnel <stefan_ml@behnel.de>
Date:   Sun Jul 5 18:35:27 2026 +0200

    Infer exception base types (GH-7783)

    Teaches Cython about Python's exception class hierarchy and allows it to
    infer a concrete exception (base) type as spanning type for two given exceptions.

    Moves the long list of known builtin type names from `Code.py` (where it
    always felt awkward) to `PyrexTypes.py`. `Builtin.py` might seem better
    but introduces import order issues since the list is used in other
    modules that `Builtin.py` depends on. It now lives right before
    `BuiltinObjectType` in `PyrexTypes.py`, which seems sufficiently appropriate.

    I also moved `uncachable_builtins` with it to help keeping that set in sight of the known builtins.
    I wonder if `renamed_py2_builtins_map` should be moved as well. It's not going to change any more.

 Cython/Compiler/Builtin.py             |  76 ++++++++++++++++----
 Cython/Compiler/Code.py                | 189 --------------------------------------------------
 Cython/Compiler/ExprNodes.py           |   4 +-
 Cython/Compiler/Nodes.py               |  23 ++++---
 Cython/Compiler/PyrexTypes.py          | 378 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----
 Cython/Compiler/Symtab.py              |   8 +--
 Cython/Compiler/Tests/TestBuiltin.py   |  29 +++++++-
 Cython/Compiler/Tests/TestTypes.py     |   1 +
 Cython/Utility/Builtins.c              | 113 ++++++++++++++++++++++++++++++
 docs/src/userguide/extension_types.rst |  23 +++++++
 tests/run/builtin_exceptions.py        | 216 +++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 tests/run/type_inference.pyx           |  60 ++++++++++++++++
 12 files changed, 882 insertions(+), 238 deletions(-)
```

```
<...>
  [56/67] Building CXX object CMakeFiles/lib.dir/lib.cpp.o
  FAILED: [code=1] CMakeFiles/lib.dir/lib.cpp.o
  /usr/bin/ccache /usr/bin/g++ -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -Dlib_EXPORTS -I/home/tcaswell/.pybuild/cp315t/include/python3.16t -I/home/tcaswell/source/p/apache/arrow/python/pyarrow/src -I/tmp/tmp6nlbqd7k/build/pyarrow/src -I/home/tcaswell/.virtualenvs/cp315t/include -I/home/tcaswell/.virtualenvs/cp315t/lib/python3.16t/site-packages/numpy/_core/include -Wno-noexcept-type -Wno-self-move  -Wall -fno-semantic-interposition -msse4.2  -fdiagnostics-color=always  -fno-omit-frame-pointer -Wno-unused-variable -Wno-maybe-uninitialized -O3 -DNDEBUG -O2 -ftree-vectorize  -std=c++20 -fPIC -Wno-unused-function -MD -MT CMakeFiles/lib.dir/lib.cpp.o -MF CMakeFiles/lib.dir/lib.cpp.o.d -o CMakeFiles/lib.dir/lib.cpp.o -c /tmp/tmp6nlbqd7k/build/lib.cpp
  /tmp/tmp6nlbqd7k/build/lib.cpp: In function ‘PyObject* __pyx_pf_7pyarrow_3lib_28set_timezone_db_path(PyObject*, PyObject*)’:
  /tmp/tmp6nlbqd7k/build/lib.cpp:33814:21: warning: ‘arrow::GlobalOptions::timezone_db_path’ is deprecated: Deprecated in 24.0.0. Only needed for Clang/libc++ on Windows. [-Wdeprecated-declarations]
  33814 |     __pyx_v_options.timezone_db_path = ((std::optional<std::string> )((std::string)__pyx_t_7));
        |                     ^~~~~~~~~~~~~~~~
  In file included from /home/tcaswell/.virtualenvs/cp315t/include/arrow/api.h:29,
                   from /tmp/tmp6nlbqd7k/build/lib.cpp:1440:
  /home/tcaswell/.virtualenvs/cp315t/include/arrow/config.h:102:30: note: declared here
    102 |   std::optional<std::string> timezone_db_path;
        |                              ^~~~~~~~~~~~~~~~
  /tmp/tmp6nlbqd7k/build/lib.cpp:33814:21: warning: ‘arrow::GlobalOptions::timezone_db_path’ is deprecated: Deprecated in 24.0.0. Only needed for Clang/libc++ on Windows. [-Wdeprecated-declarations]
  33814 |     __pyx_v_options.timezone_db_path = ((std::optional<std::string> )((std::string)__pyx_t_7));
        |                     ^~~~~~~~~~~~~~~~
  /home/tcaswell/.virtualenvs/cp315t/include/arrow/config.h:102:30: note: declared here
    102 |   std::optional<std::string> timezone_db_path;
        |                              ^~~~~~~~~~~~~~~~
  /tmp/tmp6nlbqd7k/build/lib.cpp:33814:21: warning: ‘arrow::GlobalOptions::timezone_db_path’ is deprecated: Deprecated in 24.0.0. Only needed for Clang/libc++ on Windows. [-Wdeprecated-declarations]
  33814 |     __pyx_v_options.timezone_db_path = ((std::optional<std::string> )((std::string)__pyx_t_7));
        |                     ^~~~~~~~~~~~~~~~
  /home/tcaswell/.virtualenvs/cp315t/include/arrow/config.h:102:30: note: declared here
    102 |   std::optional<std::string> timezone_db_path;
        |                              ^~~~~~~~~~~~~~~~
  /tmp/tmp6nlbqd7k/build/lib.cpp: In function ‘PyObject* __pyx_pf_7pyarrow_3lib_9MapScalar___getitem__(__pyx_obj_7pyarrow_3lib_MapScalar*, PyObject*)’:
  /tmp/tmp6nlbqd7k/build/lib.cpp:113612:24: error: ‘__Pyx_PyExc_LookupError_Check’ was not declared in this scope
  113612 |           if (!(likely(__Pyx_PyExc_LookupError_Check(__pyx_t_3)) || __Pyx_RaiseUnexpectedTypeError("LookupError", __pyx_t_3))) __PYX_ERR(3, 1192, __pyx_L1_error)
         |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /tmp/tmp6nlbqd7k/build/lib.cpp:1717:43: note: in definition of macro ‘likely’
   1717 |   #define likely(x)   __builtin_expect(!!(x), 1)
        |                                           ^
  /tmp/tmp6nlbqd7k/build/lib.cpp:113625:24: error: ‘__Pyx_PyExc_LookupError_Check’ was not declared in this scope
  113625 |           if (!(likely(__Pyx_PyExc_LookupError_Check(__pyx_t_3)) || __Pyx_RaiseUnexpectedTypeError("LookupError", __pyx_t_3))) __PYX_ERR(3, 1192, __pyx_L1_error)
         |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /tmp/tmp6nlbqd7k/build/lib.cpp:1717:43: note: in definition of macro ‘likely’
   1717 |   #define likely(x)   __builtin_expect(!!(x), 1)
        |                                           ^
<...>
```

### Code to reproduce the behaviour:

I discovered this trying to install apache arrow.  I did the bisect by hand and then asked the robot (opus 4.8) to generate a minimal reproducer and it came up with

```cython
# cython: language_level=3

def raise_lookup(i):
    raise IndexError(i) if isinstance(i, int) else KeyError(i)
```

which I confirmed generates code that compiles on on 3.2.9 and fails on 95c0c67fe2083031c387cbdefb5853e5623dc96b

### Expected behaviour

clean compile 

### OS

linux

### Python version

main branch and 3.14 branch

### Cython version

master

**Comment by scoder** [comment]
Thanks for the report. The issue originates from the exception hierarchy, which for the first time requires us to do type checks for types that are not directly referenced in the code. `KeyError` and `IndexError` are both `LookupError`s, so that's what we infer as result, but it's not named anywhere so the code needed to use that type isn't automatically included.

I'll look into it.

**Comment by tacaswell** [comment]
Thank you, can also confirm that the fix fixes the pyarrow build.
