### ISSUE TITLE
[BUG] function with fused type default argument causes gcc error

### ISSUE THREAD

**Issue by bernlu** [cython/cython#5554]
### Describe the bug

In a function taking a fused type pointer, setting the default argument of that parameter to `NULL` causes a gcc compiler error: `error: invalid conversion from ‘void*’ to ‘double*’ [-fpermissive]`. The example works fine using cython 0.29.36.

```
$ cythonize -i foo.pyx 
running build_ext
building 'foo' extension
creating /home/berneluk/cython3test/tmpy52hsl6q/home
creating /home/berneluk/cython3test/tmpy52hsl6q/home/berneluk
creating /home/berneluk/cython3test/tmpy52hsl6q/home/berneluk/cython3test
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/berneluk/cython3test/.venv/include -I/usr/include/python3.10 -c /home/berneluk/cython3test/foo.cpp -o /home/berneluk/cython3test/tmpy52hsl6q/home/berneluk/cython3test/foo.o
/home/berneluk/cython3test/foo.cpp: In function ‘int __pyx_pymod_exec_foo(PyObject*)’:
/home/berneluk/cython3test/foo.cpp:2200:14: error: invalid conversion from ‘void*’ to ‘double*’ [-fpermissive]
 2200 |   __pyx_k_ = __pyx_t_2;
      |              ^~~~~~~~~
      |              |
      |              void*
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

### Code to reproduce the behaviour:

```cython
# distutils: language=c++

ctypedef fused bar:
    double

cdef foo(bar* b=NULL):
    pass
```

### Expected behaviour

The code should compile.

### OS

Linux

### Python version

3.10.6

### Cython version

3.0.0

### Additional context

In cython 0.29.36 this code compiles as expected. I looked at the cpp files and noticed that in 3.0.0, an additional variable is generated:

```cpp
// 3.0.0
void *__pyx_t_2;
double *__pyx_k_;
// ...
/* "foo.pyx":6
 * 	double
 * 
 * cdef foo(bar* b=NULL):             # <<<<<<<<<<<<<<
 * 	pass
 */
__pyx_t_2 = NULL;
__pyx_k_ = __pyx_t_2;
```
```cpp
// 0.29.36
static double *__pyx_k_;
// ...
/* "foo.pyx":6
 * 	double
 * 
 * cdef foo(bar* b=NULL):             # <<<<<<<<<<<<<<
 * 	pass
 */
__pyx_k_ = NULL;
```
Seems like the 3.0.0 code might just be missing a `static_cast<double*>`?
