### ISSUE TITLE
[BUG] Compiler crash on nested class

### ISSUE THREAD

**Issue by JelleZijlstra** [cython/cython#4572]
**Describe the bug**
The current alpha for Cython 3 crashes on a nested class definition in a py+pxd setup.

**To Reproduce**
Code to reproduce the behaviour:
```
$ cat _red.py
class R:
    class watch_key_states:
        pass
$ cat _red.pxd
cdef class R:
    pass
$ cython -3 --line-directives -X infer_types=True _red.py
/home/jelle/ans/venv/lib/python3.6/site-packages/Cython/Compiler/Main.py:346: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/jelle/ans/web/lib/qclient/databox/_red.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
class R:
    class watch_key_states:
   ^
------------------------------------------------------------

_red.py:2:4: Compiler crash in ControlFlowAnalysis

ModuleNode.body = StatListNode(_red.py:1:0)
CClassDefNode.body = StatListNode(_red.py:2:4)

Compiler crash traceback from this point on:
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/Cython/Compiler/Visitor.py", line 180, in _visit
    return handler_method(obj)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/Cython/Compiler/FlowControl.py", line 1335, in visit_PyClassDefNode
    self.env.lookup(node.target.name))
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/Cython/Compiler/FlowControl.py", line 174, in mark_assignment
    if self.block and self.is_tracked(entry):
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/Cython/Compiler/FlowControl.py", line 152, in is_tracked
    if entry.is_anonymous:
AttributeError: 'NoneType' object has no attribute 'is_anonymous'
$ cython --version
Cython version 3.0.0a10
```

**Expected behavior**
Don't crash

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python version 3.6.10
 - Cython 3.0.0a10

**Additional context**
This works fine on 0.29.x.

**Comment by da-woods** [comment]
So if you _don't_ use pure Python mode, the following fails in both master and 0.29.x:

```
cdef class R:
    class watch_key_states:
        pass
```

with the (correct) error `class definition not allowed here`

The `cython.cclass` decorator fails (but that's expected because it'll apply to the inner class too). It also gives an unhelpful compiler crash though.

Your code does appear to work for me in 0.29.x though.

------------------------------------

Personally I think we should be consistent. Either we should say:
* a class inside a cdef class was never intended to work. We should ban it (in both pyx and in pure Python mode)
* since it appears to work, we should allow it.

I'm mildly in favour of banning it. Regular classes are normal Python code, and they do take values from their outer scope. I don't think this can work reliably inside cdef classes so there are lots of things that can go wrong when defining classes there.

**Comment by scoder** [comment]
> Regular classes are normal Python code, and they do take values from their outer scope

Class scopes do not nest, so that's not an issue.
```python
>>> class A:
...   x = 1
...   class B:
...     y = x + 1
... 
Traceback (most recent call last):
NameError: name 'x' is not defined
```

I don't think there is anything inherently wrong with defining a Python class inside of a cdef class, compared to defining a regular class variable.

**Comment by scoder** [comment]
> The `cython.cclass` decorator fails (but that's expected because it'll apply to the inner class too). It also gives an unhelpful compiler crash though.

The `@cython.cclass` decorator should not be inherited by nested classes.

**Comment by da-woods** [comment]
> The `@cython.cclass` decorator should not be inherited by nested classes.

Related: https://github.com/cython/cython/issues/4092 (I agree it shouldn't be but it was surprisingly fiddly to fix)
