### ISSUE TITLE
[BUG] Fused type memory views don't work in pure python syntax for 0.29.x

### ISSUE THREAD

**Issue by pfebrer** [cython/cython#5085]
### Describe the bug

You can declare a memory view from a fused type in cython syntax, but not in the pure python syntax.

This happens only in 0.29.x, not in 3.0.x, but since 3.0 is still in alpha our project depends on 0.29 and we find this issue.

### Code to reproduce the behaviour:

```cython
import cython
    
def test_cython_syntax(cython.floating[:] a):
    return a

def test_python_syntax(a: cython.floating[:]):
    return a
```

The `test_cython_syntax` function compiles without problems, while the `test_python_syntax` returns:

```
Error compiling Cython file:
------------------------------------------------------------
...
import cython
    
def test_cython_syntax(cython.floating[:] a):
    return a

def test_python_syntax(a: cython.floating[:]):
^
------------------------------------------------------------

/home/pfebrer/.cache/ipython/cython/_cython_magic_9d885c7c7007c8fdab3ab0aee360f02f.pyx:6:0: Compiler crash in AnalyseExpressionsTransform

File 'Nodes.py', line 435, in analyse_expressions: StatListNode(_cython_magic_9d885c7c7007c8fdab3ab0aee360f02f.pyx:1:0)
File 'Nodes.py', line 435, in analyse_expressions: StatListNode(_cython_magic_9d885c7c7007c8fdab3ab0aee360f02f.pyx:6:0)
File 'Nodes.py', line 3145, in analyse_expressions: DefNode(_cython_magic_9d885c7c7007c8fdab3ab0aee360f02f.pyx:6:0,
    modifiers = [...]/0,
    name = 'test_python_syntax',
    np_args_idx = [...]/0,
    num_required_args = 1,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)
File 'Nodes.py', line 3291, in prepare_argument_coercion: DefNodeWrapper(_cython_magic_9d885c7c7007c8fdab3ab0aee360f02f.pyx:6:0,
    args = [...]/1,
    modifiers = [...]/0,
    name = 'test_python_syntax',
    np_args_idx = [...]/0,
    num_required_args = 1)

Compiler crash traceback from this point on:
  File "/home/pfebrer/miniconda3/envs/simulations/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 3291, in prepare_argument_coercion
    if not arg.type.create_from_py_utility_code(env):
  File "/home/pfebrer/miniconda3/envs/simulations/lib/python3.8/site-packages/Cython/Compiler/PyrexTypes.py", line 903, in create_from_py_utility_code
    suffix = self.specialization_suffix()
  File "/home/pfebrer/miniconda3/envs/simulations/lib/python3.8/site-packages/Cython/Compiler/PyrexTypes.py", line 873, in specialization_suffix
    return "%s_%s" % (self.axes_to_name(), self.dtype_name)
AttributeError: 'MemoryViewSliceType' object has no attribute 'dtype_name'
```

### Expected behaviour

Both should compile the same.

### Environment

OS: Linux
Python version [e.g. 3.8.12]
Cython version [e.g. 0.29.32]

**Comment by da-woods** [comment]
I think we're unlikely to backport this. Quite a bit has changed with annotations between 0.29.x and 3.0alpha so it's increasingly hard to backport anything cleanly, and I can't even find where this was fixed based on a quick search github search (I'm sure git bisect would reveal it though).

We're generally reluctant to backport too much from Cython 3 alpha unless we're very confident of it (or unless it fixes something very serious). If we backport too much then it effectively becomes 0.29.x alpha...

**Comment by pfebrer** [comment]
Oh ok, I understand. Thanks for the answer!
