### ISSUE TITLE
`func_defaults` ignored

### ISSUE THREAD

**Issue by yunesj** [cython/cython#1531]
The following recipe from [SO](http://stackoverflow.com/a/3209862/420755) works in python 2.7.12 but not via cython 0.25.1:

`my_cython_module.py`
````
def self_reference(f):
    f.func_defaults = f.func_defaults[:-1] + (f,)
    return f

@self_reference
def g(this=None):
  this.msg = 'Success!'
````
`self_reference` replaces the default parameter for `this` to be the argument `f`. This allows `f` to store data about its computation as function attributes.

`test.py`:
````
import my_module

if __name__ == '__main__':
    my_module.g()
    print my_module.g.msg

````

Python 2.7.12:
> Success!

Cython 0.25.1:
> AttributeError: 'NoneType' object has no attribute 'msg'

From the generated C code, it appears that the parameter is initialized to its default value and possibly overridden by `args` and `vargs`, but updates to `func_defaults` are not considered.
