### ISSUE TITLE
Cython-0.27.3.tar.gz fails to build on CPython 3.7 alpha 2

### ISSUE THREAD

**Issue by dstromberg** [cython/cython#1988]
Cython-0.27.2.tar.gz would build, but not Cython-0.27.3.tar.gz.

The errors end with:
    /tmp/pip-build-0qsfp3vo/cython/Cython/Compiler/Pythran.c:9616:11: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_state'
         tstate->exc_state.exc_traceback = *tb;
               ^
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
^[[31mCommand "/usr/local/cpython-3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0qsfp3vo/cython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-whjoc62z-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0qsfp3vo/cython/^[[0m

**Comment by scoder** [comment]
Yeah, well... Just wait for alpha-3.
