### ISSUE TITLE
[INFO] Limited API and freethreading Python 3.15

### ISSUE THREAD

**Issue by da-woods** [cython/cython#7399]
It is anticipated that Python 3.15 will support a version of the Limited API that means the same extension will be importable in both regular and free-threading Python. Some of the details are still to be decided but Cython aims to support this.

To let you start testing this early I've pushed a [`freethreading-limited-api-preview`](https://github.com/cython/cython/tree/freethreading-limited-api-preview) branch to this repo. This branch is intended to be fairly short-lived and will be deleted once it's all merge into the repo.  The branch will probably not be kept rigorously up-to-date with other Cython bug fixes

It's a merge of the following PRs and branches:

- [ ] https://github.com/cython/cython/pull/7382
- [x] https://github.com/cython/cython/pull/7190
- [ ] https://github.com/cython/cython/pull/7333
- [ ] https://github.com/cython/cython/pull/7412
- [ ] https://github.com/cython/cython/pull/7410
- [ ] https://github.com/da-woods/cython/tree/cdef-class-opaque-pyobject
- [ ] Cherry-pick e03bc1095 (to allow marking a module as freethreading_compatible)
- [ ] Some memoryview-handling stuff (probably to be picked separately) e.g. 87d9cea4d8e6d, 6d0af5b6dda0a,
- [ ] Extern types 2c86e5fa2 (probably more)

Be aware that it is missing some some bits of internal thread safety which would be provided by critical sections and PyMutexes since these have not yet been added to the Limited API.

# To use

Define the following `CFLAGS` when you build:

```
-DPy_LIMITED_API=0x030F0000 -DCYTHON_OPAQUE_OBJECTS=1 -D_Py_OPAQUE_PYOBJECT
```

Build with as recent alpha of Python 3.15 as you can.

Set up your build system normally so that the modules are named `abi3.so` (see https://cython.readthedocs.io/en/latest/src/userguide/limited_api.html#building-with-the-limited-api for some hints)

# Known Limitations

Anything involving an extern type (`cdef extern class` or similar) is unlikely to work.

Performance is about 13% slower compare with the `Py_LIMITED_API=0x030E0000` - essentially every access to an attribute of a cdef class goes through a painful indirect lookup.

Some thread-safety guards missing right now.

**Comment by da-woods** [comment]
One detail that I've subsequently spotted is that it breaks our memoryview ABI compatibility. That's going to need either some workarounds or some checks.

**Comment by da-woods** [comment]
The other outstanding issue is access to cdef classes without the GIL. I've currently implemented a very hacky workaround, but there's no guarantee it'll keep working long-term and Python developers are sceptical of it.

**Comment by mgorny** [comment]
I've noticed that the generated C file has:

```c
  #if CYTHON_COMPILING_IN_CPYTHON_FREETHREADING
  {Py_mod_gil, Py_MOD_GIL_NOT_USED},
  #endif
```

rather than:

```c
  #if CYTHON_COMPILING_IN_CPYTHON_FREETHREADING || CYTHON_COMPILING_IN_LIMITED_API_FREETHREADING
  {Py_mod_gil, Py_MOD_GIL_NOT_USED},
  #endif
```

Is this intentional?

**Comment by da-woods** [comment]
@mgorny thanks for testing.

I think I deliberately didn't add it in https://github.com/cython/cython/pull/7382 because I don't think it should be in Cython master until we have access to PyMutex and critical section.

However, I think it should be available on this "preview" branch because hopefully everyone is sensible enough not know it's for testing and not for shipping. I'll push a commit to fix that shortly.

**Comment by mgorny** [comment]
Yeah, I agree. Thanks!

**Comment by da-woods** [comment]
I've pushed a mid-sized update to this.

* fixes a few bugs with vtab access
* more importantly, guards a hack related to attribute lookup without the GIL. The Python core-devs weren't hugely happy about the approach (this is fine... it's the natural equilibrium for Python core-devs to be unhappy at hacks in Cython) I'd taken because it may not be long-term stable. I've now at least got a lower-performance fallback ready if it the underlying assumption ends up changing.

I'll probably push another update later this week to try to clean up some memoryview stuff, time permitting. That'll be more code quality rather than any change in what works.

**Comment by ngoldbaum** [comment]
Over in https://github.com/cython/cython/pull/7476#issuecomment-3786577880, @da-woods pointed out that defining wrappers for PyObject subtypes like NumPy does in its Cython headers will need some work on the Cython side.

NumPy currently does something like this:

```
cdef extern from "numpy/arrayscalars.h":

    # abstract types
    ctypedef class numpy.generic [object PyObject]:
        pass
```

Maybe NumPy's cython headers will need some updates?

**Comment by da-woods** [comment]
I've pushed some improvements to the handling of extern types (e.g. numpy's `numpy.ufuncobject`). You can now specify:

```
ctypedef class numpy.generic [object PyObject, opaque_pyobject False]:  # or true
```

to explicitly specify whether the extern type opaque or not. It defaults to `False` so there's no need to specify it for existing code.
This means that non-opaque Cython modules can use opaque extern types (at least partly).

Opaque Cython modules don't check the size of non-opaque extern types. Largely because it will definitely be a compile error if you try to access their attributes, so it's "relatively" safe.

I imagine some of this will end up changing, so don't rely too much on it in this exact form. But hopefully it lets people get a bit further with the Numpy headers.

**Comment by ngoldbaum** [comment]
@da-woods I'm planning to add a section to PEP 803 that quotes ecosystem library maintainers to comment on why PEP 803 will be useful. Can you comment a bit about why it'll be beneficial for Cython users? I can then excerpt that for the PEP.

No worries if you're not comfortable doing that.

**Comment by da-woods** [comment]
@ngoldbaum I don't mind being quoted but.... I don't _fully_ understand the appeal of the Stable ABI.

Cython is doesn't have huge problems with the number of wheels we distribute because ultimately it works fine as pure-Python. We do distribute wheels for a few of the smaller platforms as Stable ABI wheels but that's more "dogfooding" than because we actually need to. So I'm adding this in anticipation that other people will find it useful rather than because I will.

I do remain slightly concerned that the performance trade-offs for this will turn out to be too much for many Cython users (it's possible that the trade-off may be different for other binding tools). That's not a huge disaster since we're not getting rid of the regular compilation mode so people are free to pick their own personal trade-offs.

But none of that makes a particularly useful quote...

**Comment by ngoldbaum** [comment]
I think it was useful! I opened https://github.com/python/peps/pull/4831.

**Comment by scoder** [comment]
> I do remain slightly concerned that the performance trade-offs for this will turn out to be too much for many Cython users

Our benchmarks report our Limited API code (the `L-` columns) as visibly slower than our optimised CPython code, e.g.

https://github.com/cython/cython/actions/runs/22303110980

Most of the big-gap ones are micro-benchmarks, but from the rest, especially object intensive benchmarks like "richards" suffer by factors. They are often slower than the non-compiled pure Python code (the column right of it). The proposed Stable ABI changes are likely to make this relation even worse, and thus completely useless for anything performance relevant. [EDIT: I was referring to code where the performance of the C-API code matters, not one-shot long running native data processing where it does not.]

I can see the "external library wrapping" use case still being a candidate for the Stable ABI, even with the new worse performance. There are certainly cases where people say "I need the functionality, regardless of the speed". PyQT comes to my mind as a reasonable example, also audio/video processing libraries etc. that just need a "configure and run". There are certainly cases like this. But in many such cases, running a subprocess will be hugely easier and faster than connecting to a library through the Limited API.

I can't say whether it's really worth building and supporting a whole second API construct just for this use case. Performance matters for a lot of users in the Python ecosystem, and this isn't just about some "~10% YMMV". Anything for which the wrapping performance matters will probably try hard to avoid the Stable ABI at all cost.

**Comment by rgommers** [comment]
> The proposed Stable ABI changes are likely to make this relation even worse, and thus completely useless for anything performance relevant.

I am not sure this take is correct in general. It seems to be true when one is using lots of short, micro-second level operations. When working with larger array data (quite common for numerical/scientific libraries), the differences quickly seem to converge to <=10%. See for example benchmarks for PyWavelets (which uses a lot of Cython code, and some C code) in https://github.com/PyWavelets/pywt/pull/828. Scikit-learn (which is even more heavy on Cython usage) benchmarks are in the works, I'd expect roughly similar outcomes.

My expectation is that for the most popular platforms, well-maintained scientific libraries are likely to continue to take the wheel building pain to avoid any performance regressions, but for niche platforms it'll be either "no wheels" or "stable ABI wheels". And for less well-maintained libraries, the tradeoffs are leaning even more towards the stable ABI being useful.

**Comment by neutrinoceros** [comment]
I agree with Ralph, but I want to add an asterisk there:

> for less well-maintained libraries*, the tradeoffs are leaning even more towards the stable ABI being useful.

*: this is also true for libraries that are very well maintained but *finished*. I have a couple small libraries that evolve so slowly that needing (essentially identical) new binaries once a year *dominates* their release cycle, and while I'm certainly interested in making them free-threading compatible, I don't want to double or triple the number of wheels I need to make just for this (still niche) target. Having a single target I could compile to and support both builds would be a game changer, and I would happily provide free-threading compatible binaries in these conditions. The performance in these libraries did not suffer *at all* from the switch to abi3, as far as I could tell; they only ever deal with large-ish arrays, with long-running hot loops and very little to no interaction with the Python runtime.

**Comment by ngoldbaum** [comment]
@da-woods I'd like to get your opinion on something. Is it perhaps problematic that opaque PyObject builds are "viral"? I was just testing [cymem](https://github.com/explosion/cymem) since it has few dependencies and a nontrivial use of `cython.critical_section`. I noticed this when I tried to use the cymem thread safety test that Lysandros came up with when we were working on free-threaded support in the explosion stack earlier this year: https://github.com/lysnikolaou/test-cymem-threadsafety.

```
    def test_concurrent_pool_operations():
>       from test_cymem_threadsafety.test_pool import test_concurrent_pool_operations

../../../../../tests/test_runner.py:2:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: Cimported type 'type' has '__cython_typeoffset__'. You are probably trying to cimport a module built with CYTHON_OPAQUE_OBJECTS set from a module without it set.

test_pool.pyx:1: TypeError
```

Here I'm building the `test-cymem-threadsafety` project with a "normal" cython build and no opaque PyObject layout.

I think that means projects who ship Cython headers will need to be very careful about shipping abi3t wheels, since it will cause downstream build breakage for anyone using the Cython headers.

Can this restriction be relaxed perhaps? If not, what do you think the guidance should be for projects that ship Cython headers? I think that includes SciPy.

**Comment by da-woods** [comment]
> I think that includes SciPy.

Just quickly looking at Scipy, I think the pxd files there are mostly functional, and don't really have `cdef classes`? If that is indeed the case, then you should be fine.

---------------------------------------

More generally:

It won't be possible to cimport a non-opaque cdef class into an opaque module. Just because you'll have no way of accessing the members.

With a bit of work, it should be possible to cimport an opaque cdef class into a non-opaque module.  The main thing we'd need to add is some way of labelling classes (or more likely modules) as opaque at compile-time. If we know that then we can ensure that all members are looked up the opaque way.

(Not directly related to freethreading or this version of the Stable ABI, but there might be some value in letting users force classes to use opaque pyobject even if the rest of the module isn't. Mainly that it allows inheritance from builtin types when using the Stable ABI.  I don't know how valuable that is though since no-one's complained about it yet).

The awkward thing is that "opaque pyobject" is set with C-compile-time flags (and realistically, people might well build and distribute versions of the same thing both with and without it). However, to handle the "opaque class cimported into non-opaque module" case, Cython would probably want to know at Cython-compile-time. I don't know what the best way to handle that is.

I'll think about it some more though....

-----------------------------------------

There's also a big incompatibility with passing typed memoryviews between opaque/non-opaque module interface. I believe that should be solveable though and so I'm working on it. (It's also good to do generally because it solves a problem where we've inadvertently made typed memoryviews very hard to change)

**Comment by rgommers** [comment]
SciPy's public Cython API (= `cython_blas`, `cython_lapack`, `cython_special`) should be functions only indeed.

**Comment by ngoldbaum** [comment]
> With a bit of work, it should be possible to cimport an opaque cdef class into a non-opaque module.

I think that would solve the virality issue I was worried about, sounds good.

**Comment by da-woods** [comment]
A few more thoughts about the viral opaque PyObject ABI issues:

# Impact

I think it's comparatively rare to share Cython-generated cdef classes between projects. So it probably isn't a huge issue. (Although I also don't have visibility on all uses, everywhere).  Until we have a good solution I'd probably recommend that projects either exporting or importing types across an external interface don't use opaque objects.

The largest project currently using the Stable ABI from Cython is probably RapidsAI.  They don't currently support free-threaded builds at all. They're composed of many different sub-packages that look to have at least some interpackage `cimports`. They also haven't completely switched to Stable ABI (because they have one component that depends on Pybind11). So they _might_ be someone that's unable to use this even if they wanted to. I'll ask them and see what they think.

The error-checking on the current implementation at least means people shouldn't be caught out and should find out quickly about this limitation.

I'm more concerned right now about typed memoryviews. Partly because I haven't yet got any good detection in place about incompatibilities, and partly because that may also affect simple function interfaces.  I've done some work on trying to improve this (because this would be nice to solve for other reasons too) but it's more complicated than I initially thought.

# Constraints

I think we're fairly constrained in what we can do to fix it:

* I don't think I can (or should) do anything that makes existing, "normal" Cython modules slower.
* For "regular" Cython modules, any class that's defined as `public` or `api` has a API constraint that it's defined in the style:

    ```
    typedef struct {
        PyObject_HEAD
        double attr1;
        int attr2;
    } struct_name;
    ```

    because we generate headers in this format. So people need to be able to write code `struct_name *o = ...; o->attr1 = ...`.
* For any class that gets `cimport`ed anywhere, we also have an ABI constraint that the structure is defined compatible with this way.
* If I was starting from scratch, I'd probably change this all to:

    ```
    typedef struct {
        double attr1;
        int attr2;
    } contents;

    typedef struct {
        PyObject_HEAD
        contents contents;
    } struct_name;
    ```

   which would be a lot easier to work with because `contents` would be identical on opaque and non-opaque builds.
   However, I don't think that's necessarily even ABI compatible according to the various standards (C++ `std::is_layout_compatible`
   certainly thinks it isn't). Practically I suspect you _might_ get away with it though.

# Current conclusions

I still think that it'll work to be able to manually mark certain types as "definitely opaque" and those should be usable from any other Cython module. But it's one way only.

I'd also be possible for modules to define an "opaque interface" which consists of types without members, and with members accessed through functions rather than directly (essentially fairly similar to what Numpy has done for their Cython definitions). In the short-term this would likely be something that authors would have to provide manually.

I don't think it's it important that this is solved immediately though - most people using Cython are mostly using it internally within a package - provided there's enough error checking to catch mistakes early.

**Comment by da-woods** [comment]
I had a bit more of a look at typed memoryviews - practically I think they are binary compatible (even if that's probably not guaranteed by the Stable ABI indefinitely). But I think it's at least a problem that can be ignored for now.  The same probably applies to any extension type without inheritance, although generalizing that assumption feels potential dodgy.

**Comment by nitzmahone** [comment]
> I do remain slightly concerned that the performance trade-offs for this will turn out to be too much for many Cython users

I'll offer another data point here from my recent playing around with PyYAML against 3.15.0a7 (FT): a basic "parse a large-ish file" benchmark using PyYAML's Cython `libyaml` extension shows a ~40% performance hit between a vanilla `cp315t` ABI build and a handcrafted `abi3.abi3t` build against the freethreading-limited-api-preview branch. PyYAML is probably a decent extreme real-world case for this, since its ancient unoptimized tokenizer spends most of its time fetching characters one by one and poking at CDef structs, so the additional attribute overhead really hurts.

That said, I'm still a strong "hell yes, please!" for Cython supporting `abi3.abi3t` builds. It's still ~ an order of magnitude faster than the pure-Python version, and with all the additional arches getting higher-tier support, I feel like we're drowning in "we want wheels for XYZ arch" requests- and of course XYZ is always something slow that requires emulation on commodity CI platforms. That's significantly blunted if each arch only needs a single wheel for everything 3.15+ for awhile rather than two for each X.Y.

I'll add my +1 to the many votes I'm seeing for "Users wanting bleeding-edge performance are free to build directly against the native ABI".

Thanks for all the work you've been doing to explore this and get it functioning!

**Comment by da-woods** [comment]
> PyYAML

Slightly off-topic for _this_ issue but you don't yet seem to be using our existing Stable ABI support? That would let you cover non-freethreading Python 3.9+ with a single wheel per-platform. (Or you could do something like we've done and have a short list of 1st tier platforms with versioned native wheels, and a longer list of 2nd tier platforms that you serve through stable ABI wheels).

**Comment by nitzmahone** [comment]
> you don't yet seem to be using our existing Stable ABI support

Oh, I'd been waiting for that for years and tracking the work with PoC's on the in-progress stuff as it was dribbling in. Thanks again for all the efforts on that- it works great!. Problem is, it landed at exactly the same time as free-threading, for which we still have to build one wheel per arch/platform/version. Cutting the build/test matrix over to a split `abi3` and `cp3XYt` setup for 3.14+ seemed like more trouble than it was worth with `abi3.abi3t` on the horizon, so I just decided to stick with status-quo + separate `t` builds until that gets sorted.

**Comment by da-woods** [comment]
I've pushed a small update to cover to use the new `Py_TARGET_ABI3T` that's in Python 3.15a3. If you set this macro then I don't think you need to set `_Py_OPAQUE_PYOBJECT`..

--------------------------------------

Some small notes about performance:
* `clang` seems to have a much smaller performance hit than `gcc`. I'm not really sure why but if you're looking to improve the performance it might be worth a try. Your results may vary of course.
* I looked into annotating the functions to get the objstruct as "pure" or [reproducible](https://en.cppreference.com/w/c/language/attributes/reproducible). The idea being that we expect to get the same result for the same object, so in principle the C compiler could optimize out multiple successive uses.

  This wasn't a great success (and thus isn't pushed): msvc doesn't support it at all, gcc appears to ignore it for anything that it can see a definition for (so I couldn't write a wrapper for `PyObject_GetTypeData` as a way of annotating it as pure). In principle it works on clang I think (or at least a toy example on godbolt does), although doesn't make a huge performance difference.

  Doing this optimization manually in Cython might be worthwhile in future, but it's pretty involved from a code-gen point of view.

**Comment by nitzmahone** [comment]
> clang seems to have a much smaller performance hit than gcc

Tried the same PyYAML "benchmark" with a gcc/clang abi3t bake-off against 3.15.0a8 (FT), the latest changes on `freethreading-limited-api-preview`, and only setting `-DPy_TARGET_ABI3T=0x030F0000 -DPy_GIL_DISABLED`. The extension built by Clang 21.1.8 was pretty consistently ~5% faster than GCC 15.2.1 on Fedora 43 x86_64. Haven't tried any profiling yet to see if that's mostly attributable to attributes (😆), but good to know.

**Comment by da-woods** [comment]
> Haven't tried any profiling yet to see if that's mostly attributable to attributes (😆), but good to know.

I didn't end up pushing the attribute changes in the end. Just experimented with them and then decided they weren't worth it.

**Comment by ngoldbaum** [comment]
3.15.0b1 came out today. However, experimentation with abi3t builds isn't yet possible because PEP 820 being accepted broke the experimental Cython support for abi3t in 3.15.0b1.

**Comment by da-woods** [comment]
Yes I'm aware of it.

I think I've got https://github.com/cython/cython/pull/7333 updated with the PEP 820 changes but haven't yet merged it back in.

The other thing that's recently added to 3.15.0b1 is support for critical sections (but not for PyMutex). I'm aiming to get that done in the near future and then update the branch here.

**Comment by da-woods** [comment]
It should be working again now. Critical section support is now in too.

**Comment by ngoldbaum** [comment]
I tested it out this morning and ran into an issue with the GIL being enabled. I think #7682 fixes it.

**Comment by ngoldbaum** [comment]
@da-woods I'm curious what your plans are to merge this branch with cython's `master` branch. Are you going to be blocked on support in build backends like setuptools? I'm a little worried setuptools at least will take a while - development has been paused for a while.

**Comment by da-woods** [comment]
I'm not quite sure.

There's some of the early bits that are pretty straightforward and I should probably just merge unilaterally.

A lot of it is pretty intrusive though (mostly in the sense that it adds a lot of macros and makes the generated code harder to read). None of it should affect the speed of the regular API code though so it shouldn't make anything worse in that regard.

> Are you going to be blocked on support in build backends like setuptools?

I don't think so. All setuptools really provides is correctly named `.so` files. Setuptools is important to us because
1. We use it as our build system. There's no proposal to distribute Cython as abi3t wheels so that bit really doesn't matter.
2. We use it in running our tests.  For running our own test suite we don't care about the names of the tested `.so` files - we can control the build perfectly well using C flags to define `Py_TARGET_ABI3T` and that's all that matters.

**Comment by ngoldbaum** [comment]
I see 3.3.0a1 just came out. It would be really nice to see this integrated before 3.3.0 final comes out.

**Comment by scoder** [comment]
> It would be really nice to see this integrated before 3.3.0 final

We're not planning to integrate this for 3.3, see https://github.com/cython/cython/issues/7753#issuecomment-4735684596

It's a large pack of changes in various corners and I do not want to risk further extending the time that it'll take us to get the pile of new features in 3.3 to our users.

I just read up on the main parts of [PEP-803](https://peps.python.org/pep-0803/), which seems to be the one that got the final blessing. It left me with the impression that independent ABIs for GIL- and noGIL-Python, and a temporal limit of the stability guarantees, seem the best path forward. As we see with abi3, we've come to a point where we can't hold up the stability guarantees – and that's fine, isn't it? Design a new replacement ABI, rebuild the packages, move on. Once a project has gone through the entire hassle to adopt _one_ Stable ABI, the next ABI adaptation will probably be mostly a rebuild, with some fixes. Projects could still ship cross-Pyversion wheels for several years, thus reducing the total number of wheels considerably, and eventual EOL-driven reduction should then keep it mostly constant over time. We'd have abi3 for Py<=3.14(non-t), abi3 and abi1t for Py3.15+, and abi4 and abi2t eventually for, say, Py3.19 or Py4.3.

The main reason why I favour independent ABIs for GIL- and noGIL-Python targets is that I found it worth adapting the code independently for the two, e.g. considering locks vs. GIL-safety, so targeting both with a single wheel seems counter-intuitive to me, at least in most cases. Why enter a critical section when the code is guarded by the GIL? There's probably enough difference between both targets to merit independently optimised wheels, and so separate ABIs are unlikely to hurt much.

**Comment by encukou** [comment]
> independent ABIs for GIL- and noGIL-Python [...] seem the best path forward

Sure. The new noGIL one happens to be compatible with the GIL, though. (Perhaps not surprising: for one, the GIL can be re-enabled; also, if the ABI should ideally be compatible with “any” future implementation, making it incompatible with the *known* past implementations would be rather questionable.)

> a temporal limit of the stability guarantees seem the best path forward

That would be nice, if we could predict when the next feature needs to break the guarantees.
Instead, CPython's ABI for the new feature got a new name.

> Why enter a critical section when the code is guarded by the GIL? There's probably enough difference between both targets to merit independently optimised wheels

In a GIL interpreter, critical sections are no-op functions in the stable ABI, and nothing (empty `#define`s) in version-specific ABI.

So, no difference until you care about the cost of a C function call, at which point you don't want the stable ABI anyway.

**Comment by da-woods** [comment]
I broadly agree that if we want to do 3.3 soon then there's too many charges here. It does essentially rewrite every attribute access to cdef classes so there's a lot to go wrong. 

I don't think the "independent ABIs" is meaningfully going to happen (or at least I was told that there was no chance of a free-threading ABI with non-opaque objects, which would be the main performance improvement).

As Petr (just) said, not omitting critical sections at compile time shouldn't cost a lot.

**Comment by nitzmahone** [comment]
Definitely understand (and appreciate) the cautious approach!

IIUC `abi3t` always == `abi3_abi3t`, so the talk of separate paths above confused me (or I'm misinformed). Just to clarify: at least for 3.3 as-currently-planned, `abi3t` is not available- only `abi3` limited API builds will be available- free-threading support continues to require version-specific builds, yeah?

**Comment by da-woods** [comment]
> Just to clarify: at least for 3.3 as-currently-planned, `abi3t` is not available- only `abi3` limited API builds will be available- free-threading support continues to require version-specific builds, yeah?

Yes. That's right.

**Comment by scoder** [comment]
>> a temporal limit of the stability guarantees seem the best path forward
>
> That would be nice, if we could predict when the next feature needs to break the guarantees.

I didn't mean to base it on prediction. When there is a good reason to change the ABI, then a decision can be taken in which (next or future) release to make that change. That release would then be the end of the current Stable ABI and the start of a new one, pretty similar to what is now happening with PEP-803. It would be a tradeoff decision between the cost of package maintenance/distribution and the cost of CPython development / language benefits / whatever the reason for the ABI change will be. Just another tradeoff, like so many others. I'm not convinced that making the object struct opaque is necessary, not right now, possibly not even in the future. It seems a premature pessimisation to me.

**Comment by encukou** [comment]
> When there is a good reason to change the ABI, then a decision can be taken in which (next or future) release to make that change. That release would then be the end of the current Stable ABI and the start of a new one, pretty similar to what is now happening with PEP-803.

That's the general plan on CPython side too --  with specifics left to be decided based on the necessary change.

> I'm not convinced that making the object struct opaque is necessary, not right now, possibly not even in the future.

Others saw non-opaque `PyObject` as [the biggest problem of `abi3`](https://github.com/capi-workgroup/problems/issues/4). It's not likely that any new stable ABI will go back to it.

**Comment by scoder** [comment]
> > I'm not convinced that making the object struct opaque is necessary, not right now, possibly not even in the future.
> 
> Others saw non-opaque `PyObject` as [the biggest problem of `abi3`](https://github.com/capi-workgroup/problems/issues/4).

I had skimmed through that issue, and sure, making the object struct opaque is _one_ of the options. Whether it's a good one depends on which side of the ABI you stand on.

The issue's problem statement specifically refers to implementing immortal object in CPython in Py3.11/12. If a new Stable ABI4 based on new, optimised object struct layouts had been defined at that point, it could already have served for four release series since then, probably even beyond Py3.15(non-t). Some 4-6 years is a reasonable time frame for a stability guarantee that most maintainers and distributors could probably live with.

Opaque object structs are really a political decision, not a technical necessity.

**Comment by dalcinl** [comment]
@scoder I'm not sure whether this is the best place to report, but looks like the following is a trivial code generation bug?
```
In file included from /usr/include/python3.15/Python.h:82,
                 from src/mpi4py/MPI.c:19:
/usr/include/python3.15/slots.h:54:58: error: braced-group within expression allowed only inside a function
   54 |     {(NAME), PySlot_INTPTR | PySlot_STATIC, {0}, {(void*)(VALUE)}}
      |                                                          ^
src/mpi4py/MPI.c:273395:5: note: in expansion of macro ‘PySlot_PTR_STATIC’
273395 |     PySlot_PTR_STATIC(Py_mod_state_free, {cleanup_func}),
       |     ^~~~~~~~~~~~~~~~~
```

The following patch fixes the error above, but...
```diff
I'm using Python 3.150.rc1, so I guess your branch is currently outdated.
diff --git a/Cython/Compiler/ModuleNode.py b/Cython/Compiler/ModuleNode.py
index 6fe3ff5c3..ede2ec496 100644
--- a/Cython/Compiler/ModuleNode.py
+++ b/Cython/Compiler/ModuleNode.py
@@ -3858,7 +3858,7 @@ class ModuleNode(Nodes.Node, Nodes.BlockNode):
         code.putln(f"  PySlot_PTR_STATIC(Py_mod_state_traverse, {Naming.module_cname}_traverse),")
         code.putln(f"  PySlot_PTR_STATIC(Py_mod_state_clear, {Naming.module_cname}_clear),")
         if Options.generate_cleanup_code:
-            code.putln("  PySlot_PTR_STATIC(Py_mod_state_free, {cleanup_func}),")
+            code.putln("  PySlot_PTR_STATIC(Py_mod_state_free, cleanup_func),")
         code.putln("#endif")
         code.putln(f"PySlot_PTR_STATIC(Py_mod_slots, {Naming.pymoduledef_slots_cname}),")
         code.putln("PySlot_PTR_STATIC(Py_slot_end, 0)")
```
... but a new error pops up:

```
In file included from /usr/include/python3.15/Python.h:82,
                 from src/mpi4py/MPI.c:19:
src/mpi4py/MPI.c:273395:42: error: ‘cleanup_func’ undeclared here (not in a function)
273395 |     PySlot_PTR_STATIC(Py_mod_state_free, cleanup_func),
       |                                          ^~~~~~~~~~~~
/usr/include/python3.15/slots.h:54:59: note: in definition of macro ‘PySlot_PTR_STATIC’
   54 |     {(NAME), PySlot_INTPTR | PySlot_STATIC, {0}, {(void*)(VALUE)}}
      |                                                           ^~~~~
error: command '/usr/lib64/mpich/bin/mpicc' failed with exit code 1
```

**Comment by da-woods** [comment]
That looks like it's missing the `f` to make it an fstring. I'll push a fix in a bit. I don't think cleanup_func is used much so obviously isn't well-tested

**Comment by da-woods** [comment]
It's worth bearing in mind that it doesn't look to mix hugely well with module state (https://github.com/cython/cython/issues/7905) - access to `cdef class` attributes won't work outside the GIL. That probably won't be fixed soon (because the work needs to happen on the module-state side rather than the freethreading limited API side). So what you're testing may be disappointing.

Either way, the immediate fix is pushed.

**Comment by dalcinl** [comment]
@da-woods After your fix, my first try with my project (mpi4py) was a complete success. Too good to be true? I'll double check everything.

However, there is a minor issue with the code generated with this branch. If you have Cython code using the special `__weakref__` attribute to support weak references, and then you compile **WITHOUT** `Py_LIMITED_API`/`Py_TARGET_ABI3T` (in other words, with CYTHON_OPAQUE_OBJECTS turn off), then C code dealing with the access of `__weakref__` in parent/child classes is broken.

Here you have a minimal reproducer:
```cython
ctypedef api class Parent [
    type   Parent_Type,
    object ParentObject,
]:
    cdef object __weakref__

ctypedef api class Child(Parent) [
    type   Child_Type,
    object ChildObject,
]:
    pass
```

And this is the error attempting to compile that code with cythonize.py
```console
[dalcinl@localhost cython]$ python --version
Python 3.14.7
[dalcinl@localhost cython]$ ./cythonize.py -b repro.pyx
Compiling /home/dalcinl/Devel/REPOS/cython/repro.pyx because it changed.
[1/1] Cythonizing /home/dalcinl/Devel/REPOS/cython/repro.pyx
In file included from /home/dalcinl/Devel/REPOS/cython/repro.c:41:
/home/dalcinl/Devel/REPOS/cython/repro.c: In function ‘__Pyx_modinit_Exttype_ChildObject’:
/home/dalcinl/Devel/REPOS/cython/repro.c:4586:131: error: ‘struct ChildObject’ has no member named ‘__weakref__’
 4586 |   if (__pyx_mstate->__pyx_ptype_5repro_Child->tp_weaklistoffset == 0) __pyx_mstate->__pyx_ptype_5repro_Child->tp_weaklistoffset = offsetof(struct ChildObject, __weakref__);
      |                                                                                                                                   ^~~~~~~~
error: Command '['gcc', '-fno-strict-overflow', '-Wsign-compare', '-DDYNAMIC_ANNOTATIONS_ENABLED=1', '-DNDEBUG', '-fcf-protection', '-fexceptions', '-fcf-protection', '-fexceptions', '-fcf-protection', '-fexceptions', '-O3', '-fPIC', '-I/usr/include/python3.14', '-c', '/home/dalcinl/Devel/REPOS/cython/repro.c', '-o', 'build/temp.linux-x86_64-cpython-314/home/dalcinl/Devel/REPOS/cython/repro.o']' returned non-zero exit status 1.
```

~Looks like a simple scope lookup issue? `offsetoff` should use the parent class that defines `__weakref__`.~
EDIT: No, it is not that simple. The `entry.cname` no longer include the `__pyx_base.prefix`, that's why the currently generated C code fails.

**Comment by da-woods** [comment]
> However, there is a minor issue with the code generated with this branch. If you have Cython code using the special `__weakref__` attribute [...]

Fixed

**Comment by dalcinl** [comment]
@da-woods Thanks! Now I can confirm that everything is working OK with mpi4py. The ABI3T build passes all tests with both the GIL-enabled or the free-threaded interpreter. The generated C code builds fine with non-ABI3 from Python 3.10 to 3.15.
