### PR TITLE
First attempt at explicit fallthrough annotation.

### PR DESCRIPTION
**Pull request by robertwb**

### CODE REVIEW

**Comment by asavah** [comment]
This produces a strange error while crosscompiling for ARM (raspberry pi3) with gcc 7.1.x

```
 arm-rpi3-linux-gnueabihf-gcc -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -pipe -Wno-unused-value -Wno-unused-but-set-variable -Wno-deprecated-declarations -fno-strict-aliasing -flto=16 -ffat-lto-objects -DPIC -fPIC -I/home/asavah/kross/build/rpi3/rootfs/usr/include/python2.7 -c /home/asavah/kross/src/cython/Cython/Plex/Scanners.c -o build/temp.armv8-rpi3-linux-gnueabihf-2.7/home/asavah/kross/src/cython/Cython/Plex/Scanners.o
/home/asavah/kross/src/cython/Cython/Plex/Scanners.c: In function ‘__pyx_pw_6Cython_4Plex_8Scanners_7Scanner_1__init__’:
/home/asavah/kross/src/cython/Cython/Plex/Scanners.c:404:34: warning: ‘fallthrough’ attribute not followed by ‘;’ [-Wattributes]
       #define CYTHON_FALLTHROUGH __attribute__ ((fallthrough))
                                  ^
/home/asavah/kross/src/cython/Cython/Plex/Scanners.c:1581:9: note: in expansion of macro ‘CYTHON_FALLTHROUGH’
         CYTHON_FALLTHROUGH
         ^~~~~~~~~~~~~~~~~~
/home/asavah/kross/src/cython/Cython/Plex/Scanners.c:1582:9: error: expected identifier or ‘(’ before ‘case’
         case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
         ^~~~
```
1000 of them and the build eventually fails,
however host cython build fine with gcc 6.3

Small change of 
```
code.putln('CYTHON_FALLTHROUGH')
```
to (added ';' as the warning suggests)
```
code.putln('CYTHON_FALLTHROUGH;')
```
fixes the error.
Don't know if it's gcc bug or shiny new feature.

Just to let you know.
