### ISSUE TITLE
[BUG] PyEval_EvalCode() signature changed in PyPy 3.7.4

### ISSUE THREAD

**Issue by GiovanniBussi** [cython/cython#4234]
**Describe the bug**

Cython 0.29.23 does not work correctly with pypy >= 3.7.4 if there is an `exec()` command in the pyx file and if C++ compiler is used. To the best of my understanding, this is related to a cast that was needed as a workaround for pypy<3.7.4 but is [not needed anymore](https://foss.heptapod.net/pypy/pypy/-/commit/d5c6dc6817c4d44fe392aebb322087bb350ab2d4) in pypy>=3.7.4. This workaround has been already removed in cython master branch [here](https://github.com/cython/cython/commit/1027db04fb7c5bbfea2b9bcdfce0b1f384e26a93#diff-11f7af60992f9e640ea52fb75d02b03c1521f07685948e95b46df97e743d82f2). I would suggest to backport this fix also to cython 0.29.x.

**To Reproduce**
Code to reproduce the behaviour:
```bash
echo 'exec("a=2; print(a)")' > demo.pyx
cat > setup.py << EOF
from distutils.core import setup, Extension
from Cython.Build import cythonize

setup (name = 'PackageName',
       version = '1.0',
       description = 'This is a demo package',
       ext_modules=cythonize(Extension(name="demo",sources=["demo.pyx"],language="c++"),language_level=3)
       )
EOF
pypy setup.py build
```

**Expected behavior**
With pypy 3.7.4 I see the following error:
```
demo.cpp:1568:18: error: no matching function for call to 'PyPyEval_EvalCode'
        result = PyEval_EvalCode((PyCodeObject *)o, globals, locals);
                 ^~~~~~~~~~~~~~~
/Users/bussi/.conda/envs/pypy37/include/pypy_decl.h:266:25: note: expanded from macro 'PyEval_EvalCode'
#define PyEval_EvalCode PyPyEval_EvalCode
                        ^~~~~~~~~~~~~~~~~
/Users/bussi/.conda/envs/pypy37/include/pypy_decl.h:267:30: note: candidate function not viable: no known conversion from 'PyCodeObject *' to 'struct _object *' for 1st
      argument
PyAPI_FUNC(struct _object *) PyEval_EvalCode(struct _object *arg0, struct _object *arg1, struct _object *arg2);
                             ^
/Users/bussi/.conda/envs/pypy37/include/pypy_decl.h:266:25: note: expanded from macro 'PyEval_EvalCode'
#define PyEval_EvalCode PyPyEval_EvalCode
```

With pypy 3.7.3 the extension can be compiled correctly. Notice that if I build a C extension (rather than a C++ one) a warning is issued but compilation succeeds. So this is visible only with the following combination:
- cython < 3
- C++ extension
- pypy >= 3.7.4
- an `exec()` instruction in the pyx file

**Environment (please complete the following information):**

I reproduced it on my MacOS, cython 0.29.23 and pypy 3.7.3 (working) or 3.7.4 (not working). However, the same happened in a more complicated context within a range of operating systems using the same version of Pypy, as it can be seen in the logs of this [pull request on conda-forge](https://github.com/conda-forge/py-plumed-feedstock/pull/17).

**Comment by mattip** [comment]
As a temporary work-around, I submitted a PR to patch the cython released with conda-forge with an appropriate patch.

**Comment by mattip** [comment]
I think this should be closed.

**Comment by scoder** [comment]
Fix backported to 0.29.x (for 0.29.28) in https://github.com/cython/cython/commit/2d287a6191bbba1e120ba9240b24ce364c443204
