### ISSUE TITLE
[BUG] Cython compiles code but then does not find the right extension type method

### ISSUE THREAD

**Issue by adam2392** [cython/cython#5226]
### Describe the bug

I run the following code:

```
import numpy as np
from . import _test

if __name__ == '__main__':
    crit = _test.Criterion()
    splitter = _test.Splitter(crit, 0)

    X = np.array([[0., 1], [0, 0]])
    splitter.test(X)
```

 and get the error:

```
  File "sklearn/tree/_test.pyx", line 21, in sklearn.tree._test.Splitter.init
    self.criterion.init()
AttributeError: 'sklearn.tree._test.Criterion' object has no attribute 'init'
Exception ignored in: 'sklearn.tree._test.Splitter.test'
Traceback (most recent call last):
  File "sklearn/tree/_test.pyx", line 21, in sklearn.tree._test.Splitter.init
    self.criterion.init()
AttributeError: 'sklearn.tree._test.Criterion' object has no attribute 'init'
```

I am trying to implement an object-oriented approach for using two extension type classes together (BaseCriterion and BaseSplitter). The `BaseSplitter` would use any subclass of `BaseCriterion` because it does not need access to the `init` function. However, if you use a `Splitter`, then the `Criterion` should be used. The code compiles and builds with Cython v0.29.33, but results in the error message shown.

### Code to reproduce the behaviour:

My `_test.pxd` file:

```cython
cdef class BaseCriterion:
    """Abstract interface for criterion."""
    cdef double A 

cdef class Criterion(BaseCriterion):
    cdef int init(self) except -1

cdef class BaseSplitter:
    """Abstract interface for splitter."""

    # Internal structures
    cdef public BaseCriterion criterion  # Impurity criterion
    cdef public double max_features      # Number of features to test

cdef class Splitter(BaseSplitter):
    cdef const double[:, ::1] X

    cdef int init(
        self,
        object X
    ) except -1

    # used to test the program in Python
    cpdef int test(self, object X)
```

and my `_test.pyx` file:

```cython
cdef class BaseCriterion:
    def __cinit__(self):
        self.A = 0.

cdef class Criterion(BaseCriterion):
    cdef int init(self) except -1:
        self.A = 1.


cdef class BaseSplitter:
    def __cinit__(self, BaseCriterion criterion, double max_features):
        self.criterion = criterion
        self.max_features = max_features

cdef class Splitter(BaseSplitter):
    cdef int init(
        self,
        object X
    ) except -1:
        self.X = X
        self.criterion.init()
        return 0

    cpdef int test(self, object X):
        return self.init(X)
```

### Expected behaviour

I would expect either a compilation error message, or for this to work as expected, since the Criterion class was used.

### Environment

OS: macOS 13.1 (22C65)
Python version 3.9
Cython version 0.29.33

### Additional context

Happy to help submit PR(s) if that helps.

**Comment by da-woods** [comment]
No. This is correct. `init` is a `cdef` function and so is only visible from Cython code but is not visible from Python code.

If you want it to be visible from Python then leave it as a `def` function (or make it a `cpdef` function, but honestly `def` is the right answer most of the time)

**Comment by scoder** [comment]
The problem is here:
> ```cython
> cdef class BaseCriterion:
>     """Abstract interface for criterion."""
>     cdef double A 
> 
> cdef class Criterion(BaseCriterion):
>     cdef int init(self) except -1
> 
> cdef class BaseSplitter:
>     """Abstract interface for splitter."""
> 
>     # Internal structures
>     cdef public BaseCriterion criterion  # Impurity criterion
>     cdef public double max_features      # Number of features to test
> ```

Note that the `criterion` attribute is defined as `BaseCriterion`, which does not have an `init` method. Thus, Cython will have to look up the name through Python, which cannot see `cdef` methods.

You could define a common `init` method in `BaseCriterion`, though, and override it in `Criterion`.

**Comment by adam2392** [comment]
Ah I see. So the issue is that I currently `BaseSplitter` would use only `BaseCriterion` methods and attributes, while `Splitter` would also have access to an additional `Criterion` attribute. However, because the attribute is defined as a `BaseCriterion`, it's looking for the method signature within that class rather than the `Criterion` class...

The options I can think of (that prolly don't work) are:
1. overriding `cdef public BaseCriterion criterion` and redefining in the `Splitter` definition: I don't think this is allowed in Cython
2. overriding the `init` function with different arguments in `BaseCriterion` and `Criterion`: I also don't think this is possible because method signatures must match exactly(?)
3. re-designing how Splitter and BaseSplitter uses BaseCriterion/Criterion

On a related note, is there any roadmap for including the ability to do C++ templating in Cython after 3.0?

**Comment by adam2392** [comment]
Another issue is that shouldn't the code not compile then when running `cython _test.pyx ...`?

**Comment by da-woods** [comment]
> Another issue is that shouldn't the code not compile then when running cython _test.pyx ...?

No - if Cython can't work out a compile-time call then it falls back to the Python-like runtime call.

Your easiest option is probably a cast:

```
        <Splitter?>(self.criterion).init()
```

This'll raise a runtime error if it isn't true

> On a related note, is there any roadmap for including the ability to do C++ templating in Cython after 3.0?

Not sure quite what you mean but probably not in the immediate future

**Comment by adam2392** [comment]
Sorry I know I shouldn't continue commenting on a closed issue. But last one for completeness

> Your easiest option is probably a cast:
> 
> ```
>         <Splitter?>(self.criterion).init()
> ```

For completeness, unfortunately this does not work:

```
Exception ignored in: 'sklearn.tree._test.Splitter.test'
Traceback (most recent call last):
  File "sklearn/tree/_test.pyx", line 21, in sklearn.tree._test.Splitter.init
    <Criterion>(self.criterion).init()
AttributeError: 'sklearn.tree._test.Criterion' object has no attribute 'init'
```

> > On a related note, is there any roadmap for including the ability to do C++ templating in Cython after 3.0?
> 
> Not sure quite what you mean but probably not in the immediate future

Sorry I meant C++ class templates. As in one can define in pure Cython (not C++) that a cdef class has some arbitrary attribute or function headers, which can be overridden in a subclass.

**Comment by da-woods** [comment]
> For completeness, unfortunately this does not work:

Brackets in the wrong place, sorry

```
(<Criterion?>(self.criterion)).init()
```

(in the first version it was casting the result of init to a `Criterion`, in this version it does the cast then calls `init`
