### ISSUE TITLE
error: ‘__Pyx_Method_ClassMethod’ undeclared introduced in Cython 0.25?

### ISSUE THREAD

**Issue by frensjan** [cython/cython#1510]
I have cythonized [cloudpickle](https://github.com/cloudpipe/cloudpickle). The pyx I created compiles fine with Cython 0.24.1 but doesn't with Cython 0.25.x:

```bash
$ ./setup.py build_ext --inplace
running build_ext
building 'bndl.util.cycloudpickle' extension
gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/frens-jan/Workspaces/tgho/bndl/venv/include -I/usr/include/python3.5m -c bndl/util/cycloudpickle.c -o build/temp.linux-x86_64-3.5/bndl/util/cycloudpickle.o
bndl/util/cycloudpickle.c: In function ‘PyInit_cycloudpickle’:
bndl/util/cycloudpickle.c:36050:52: error: ‘__Pyx_Method_ClassMethod’ undeclared (first use in this function)
   __pyx_t_5 = __Pyx_CFunc_object____object___to_py(__Pyx_Method_ClassMethod); if (unlikely(!__pyx_t_5)) __PYX_ERR(0, 1281, __pyx_L1_error)
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~
bndl/util/cycloudpickle.c:36050:52: note: each undeclared identifier is reported only once for each function it appears in
error: command 'gcc' failed with exit status 1


(venv) frens-jan bndl $ pip install Cython==0.24.1
Collecting Cython==0.24.1
  Downloading http://localshop.priv.tgho.nl/repo/tgho/download/Cython/30757/Cython-0.24.1-cp35-cp35m-manylinux1_x86_64.whl (6.5MB)
    100% |████████████████████████████████| 6.5MB 170kB/s 
Installing collected packages: Cython
  Found existing installation: Cython 0.25.1
    Uninstalling Cython-0.25.1:
      Successfully uninstalled Cython-0.25.1
Successfully installed Cython-0.24.1

$ rm -rf bndl/util/cycloudpickle.c

$ ./setup.py build_ext --inplace
Compiling bndl/util/cycloudpickle.pyx because it changed.
[1/1] Cythonizing bndl/util/cycloudpickle.pyx
running build_ext
building 'bndl.util.cycloudpickle' extension
gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/frens-jan/Workspaces/tgho/bndl/venv/include -I/usr/include/python3.5m -c bndl/util/cycloudpickle.c -o build/temp.linux-x86_64-3.5/bndl/util/cycloudpickle.o
gcc -pthread -shared -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld build/temp.linux-x86_64-3.5/bndl/util/cycloudpickle.o -L/usr/lib64 -lpython3.5m -o build/lib.linux-x86_64-3.5/bndl/util/cycloudpickle.cpython-35m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.5/bndl/util/cycloudpickle.cpython-35m-x86_64-linux-gnu.so -> bndl/util
```

From the release notes I couldn't figure out what changed.

The 'offending' source code is the last line of:
```python
    def save_classmethod(self, obj):
        try:
            orig_func = obj.__func__
        except AttributeError:  # Python 2.6
            orig_func = obj.__get__(None, object)
            if isinstance(obj, classmethod):
                orig_func = orig_func.__func__  # Unbind
        self.save_reduce(type(obj), (orig_func,), obj=obj)
    dispatch[classmethod] = save_classmethod
```

```save_classmethod``` is a method of ```cdef class CloudPickler(Pickler)```. Changing from a cdef class to a 'regular' class doesn't make a difference.

If anyone can point out my error / what went wrong? Highly appreciated!

**Comment by frensjan** [comment]
Apparently easily fixed with:
```python
from builtins import classmethod, staticmethod
```

**Comment by robertwb** [comment]
This is still certainly a bug.
