### ISSUE TITLE
[BUG] class method with std::vector default argument generates invalid c++ code

### ISSUE THREAD

**Issue by bernlu** [cython/cython#5553]
### Describe the bug

Given the MWE below, cython 3.0 will generate invalid c++ code which does not compile.

```
$ cythonize -i NoneError.pyx
Compiling /home/berneluk/cython3test/NoneError.pyx because it changed.
[1/1] Cythonizing /home/berneluk/cython3test/NoneError.pyx
/home/berneluk/cython3test/.venv/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/berneluk/cython3test/NoneError.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'NoneError' extension
creating /home/berneluk/cython3test/tmpymjkwm47/home
creating /home/berneluk/cython3test/tmpymjkwm47/home/berneluk
creating /home/berneluk/cython3test/tmpymjkwm47/home/berneluk/cython3test
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/berneluk/cython3test/.venv/include -I/usr/include/python3.10 -c /home/berneluk/cython3test/NoneError.cpp -o /home/berneluk/cython3test/tmpymjkwm47/home/berneluk/cython3test/NoneError.o
/home/berneluk/cython3test/NoneError.cpp: In function ‘int __pyx_pymod_exec_NoneError(PyObject*)’:
/home/berneluk/cython3test/NoneError.cpp:4109:37: error: ‘None’ was not declared in this scope
 4109 |   __pyx_k_ = ((std::vector<double> )None);
      |                                     ^~~~
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

```

The example is working using cython 0.29.36. There is a workaround for this problem as well, see *additional context*.

### Code to reproduce the behaviour:

```cython
# distutils: language=c++

from libcpp.vector cimport vector

cdef class Foo:
    def bar(self, vector[double] b = vector[double]()):
        pass

```

### Expected behaviour

This example should generate valid cpp code.

### OS

Linux

### Python version

3.10.6

### Cython version

3.0.0

### Additional context

This is a weird edge case. Defining the function the exact same way outside of a class compiles, as does initializing a variable like `cdef vector[double] b = vector[double]()`

There is a workaround: if one instead chooses `()` as default argument like this, the resulting code is valid and compiles:
```cython
# distutils: language=c++

from libcpp.vector cimport vector

cdef class Foo:
    def bar(self, vector[double] b = ()):
        pass
```

**Comment by da-woods** [comment]
This bisects to ee7ae0b9ce0dea51cf17adf119afe439917ee4c0

**Comment by da-woods** [comment]
Fixed in https://github.com/cython/cython/commit/292c72c70171720be35b159a9afc9e338633afc5
