### PR TITLE
Avoid conflict between int-to-py and anonymous-enum-to-py

### LINKED ISSUE #5623: [BUG] Duplicate `__Pyx_PyInt_As_int` functions
### Describe the bug

We are having an issue when migrating to recent Cython 3.0.  The compiler issues the next error:

```
/Users/faltet/blosc/python-blosc2/_skbuild/macosx-13.0-arm64-3.11/cmake-build/blosc2/blosc2_ext.c:71562:28: error: redefinition of '__Pyx_PyInt_As_int'
  static CYTHON_INLINE int __Pyx_PyInt_As_int(PyObject *x) {
                           ^
/Users/faltet/blosc/python-blosc2/_skbuild/macosx-13.0-arm64-3.11/cmake-build/blosc2/blosc2_ext.c:69734:28: note: previous definition is here
  static CYTHON_INLINE int __Pyx_PyInt_As_int(PyObject *x) {
                           ^
2 warnings and 1 error generated.
make[2]: *** [blosc2/CMakeFiles/blosc2_ext.dir/blosc2_ext.c.o] Error 1
make[1]: *** [blosc2/CMakeFiles/blosc2_ext.dir/all] Error 2
make: *** [all] Error 2

```

### Code to reproduce the behaviour:

You can reproduce the issue by going to the python-blosc2 project at: https://github.com/Blosc/python-blosc2 and compile the extension with regular:

```bash
python setup.py build_ext -j 8 -i
```

### Expected behaviour

We are expecting a successful compilation.  Actually, we are using Cython < 3 for many years, and never had this issue before.

### OS

macOSX, Linux

### Python version

any

### Cython version

3.0.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by da-woods**
Introduced in dec61cdd222ded6d5f96a635d9c4b0dddcbc4e78 (where `IS_ENUM` was introduced, which meant the implementation diverged but the name stayed the same)

Fixes #5623

### CODE REVIEW

File: tests/run/c_int_types_T255.pyx [hunk 1]
```diff
@@ -765,6 +765,20 @@ def test_convert_pylong(x):
...
    return r
 
+
+cdef enum:
+   ANONYMOUS_ENUM_MEMBER = 1
+
+def test_anonymous_enum():
+   """
+   The main point here is that the from-py conversion function shouldn't
+   conflict with in
```
Comment (h-vetinari) [inline tests/run/c_int_types_T255.pyx:775]: with in -> with int?

File: Cython/Compiler/PyrexTypes.py [hunk 2]
```diff
@@ -59,7 +59,8 @@ def specialization_name(self):
         if self._specialization_name is None:
             # This is not entirely robust.
             common_subs = (self.empty_declaration_code()
-                           .replace("unsigned ", "unsigned_")
+                           # covers both "unsigned " amd "signed "
+                           .replace("signed ", "signed_")
```
Comment (h-vetinari) [inline Cython/Compiler/PyrexTypes.py:63]: amd -> and

Comment (da-woods) [reply Cython/Compiler/PyrexTypes.py]: Thanks. This a fairly small PR to manage to fit two typos into
