### ISSUE TITLE
[BUG] `check_extensions_lists` Fails `isintance` Check Depending on Import Order

### ISSUE THREAD

**Issue by adam-grant-hendry** [cython/cython#4724]
**Describe the bug**
Importing `Cython` before `setuptools` causes the `isinstance` check in [`distutils.command.check_extensions_list`](https://github.com/python/cpython/blob/a43fd45918cef48187053d7c56d3b9bb902151d0/Lib/distutils/command/build_ext.py#L342) to fail because [`setuptools` overrides the `distutils.extension.Extension` class](https://github.com/pypa/setuptools/blob/e5552d3c42eddc463788861ae4c8847183eeec1c/setuptools/extension.py#L30).

[PEP 8](https://peps.python.org/pep-0008/#imports) code formatters (e.g. `black`, `isort`) sort imports alphabetically. Alphabetization is not a requirement of PEP 8, but added in these formatters for enhanced readability. To date, there are no easy ways (e.g. in vscode `settings.json`) to not format specific files. Particularly if auto-formatting on save, this makes checking in code problematic because it is not immediately apparent why the code breaks after being saved.

The earliest similar issue related to this one is [#1507](https://github.com/cython/cython/issues/1507), however this was concerning Cython 0.25.1 and this issue exists (at least in) Cython 0.28.29. 

**MRE (Minimal Reproducible Example):**

```cython
from Cython.Build import cythonize
from setuptools import find_packages, setup

ext_modules = cythonize(
    module_list="*.pyx",
    language_level=3,
)

setup(
    name="my_ext_module",
    version="0.1.0",
    ext_modules=ext_modules,
    zip_safe=False,
    package=find_packages(),
)
```

**Output:**

```bash
> py setup.py build_ext -i
running build_ext
error: each element of 'ext_modules' option must be an Extension instance or 2-tuple
```

**Temporary Fix:**
```cython
# setuptools must be imported before Cython
from setuptools import find_packages, setup
from Cython.Build import cythonize

...
```

Alternatively, re-monkeypatching `distutils.extension.Extension` in `setup.py` has been done to solve this same issue in the [`pyvision` project](https://github.com/cvondrick/pyvision/commit/07604f4445683365c5bee57a2276aebe05c244d4):

```cython
from distutils.extension import Extension as _Extension
from setuptools import setup 
distutils.extension.Extension = _Extension
distutils.command.build_ext.Extension = _Extension
Extension = _Extension
from Cython.Distutils import build_ext 

...
```

**Expected behavior**
Cython `cythonize` properly compiles extension modules regardless of import order w.r.t `setuptools`.

**Environment:**  
 - OS: Windows 10
 - Python: 3.8.10 (64-bit)
 - Cython: 0.29.28

**Additional context**
Turning off code formatting makes checking in code in larger project problematic. Without in-depth knowledge of `setuptools` and `distutils`, the error message returned by `setuptools` is confusing and does not help in fixing the actual problem.

IMO, relying on import order defeats many of the reason to have modules in python at all (and is not a full-proof solution):

- `cpython` modules are source files compiled independently of the translation units that import them
- an imported module should have no effect on the compilation of the translation unit that imports the module
- you should be able to import modules in any order without concern for redefinition of module items
