### ISSUE TITLE
Dependencies.py will not build against Python3.9

### ISSUE THREAD

**Issue by aixtools** [cython/cython#3266]
Get this error (as promised by CPython):

```
  File "/python/Cython-0.29.14/Cython/Build/Dependencies.py", line 754, in create_extension_list
    elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'

```

To get past this I added

`import collections.abc`

and modified line 754 (now 755) to read:
`    elif isinstance(patterns, basestring) or not isinstance(patterns, collections.abc.Iterable):`

After these corrections, the module built against the CPython-3.9 (master branch).

FYI

**Comment by da-woods** [comment]
https://github.com/cython/cython/commit/35fe19096c223b65ba3dfb4b7df185e2389b1f87#diff-7709661204b9afb11dad99f803bb188a

**Comment by aixtools** [comment]
looks good! So I'll close - as already fixed, just waiting!

**Comment by numpde** [comment]
I had the same problem:

`pip install cython` (_Python 3.9.0a1_ and _pip 19.3.1_) fails with **AttributeError: module 'collections' has no attribute 'Iterable'**. 

but was unable to find this before attempting to open a new issue and being referred here by the "Related Issues" feature.

**Comment by da-woods** [comment]
@aixtools I wonder if it's worth re-opening this issue mainly as a prompt for the fix to make it into the next release (otherwise it'll probably end up waiting until Cython 3 which is possibly a bit longer term)

**Comment by aixtools** [comment]
Sounds like a good idea to reopen then - if that is the way for this to be sooner, rather than (much) later.

**Comment by aixtools** [comment]
Hmm. I was going to try and get a PR for this ready - however - as this is already in master branch since last March - it seems rather pointless to make a PR based on the latest tag.

So, a friendly request to make this (small) change - sooner rather than later - as it hampers any testing with 3.9.

Thanks!

**Comment by scoder** [comment]
I picked the fix for 0.29.15.

**Comment by nekokatt** [comment]
Is there a time frame for when this will be available to be released? Not overly familiar with how often releases are made on this project is all.

Thanks :)

**Comment by tirkarthi** [comment]
I could see `0.29.15` tagged on GitHub but not pushed to PyPI. Can a release be pushed? It causes build error for scipy and projects with scipy as dependency cannot build on Python 3.9 in CI.

**Comment by scoder** [comment]
The MacOS wheel build is currently failing. There will be a release as soon as this problem is resolved.
