### ISSUE TITLE
[BUG] can't use Python bool type in return type annotations

### ISSUE THREAD

**Issue by tristan957** [cython/cython#3857]
**Describe the bug**
I cannot use the Python bool type in return type annotations, but I can use it in parameter annotations.

**To Reproduce**
Code to reproduce the behaviour:
```cython
def read(x: bool) -> Tuple[bytes, Optional[bytes], bool]:
  return b'', b'', x
```

**Expected behavior**
I expect to be able to use the Python `bool` type in return type annotations.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.6.8
 - Cython version 0.28.1

**Additional context**
Here is the Cython error after building
```
Error compiling Cython file:
------------------------------------------------------------
...
    # Compiler error when using Tuple[bytes, Optional[bytes], bool/bint]
    # When we move to Python >= 3.8, use
    # Tuple[bytes, bytes, Union[Literal[True], Literal[False]]] as a workaround
    def read(self) -> Tuple[bytes, Optional[bytes], bool]:
                                                   ^
------------------------------------------------------------

hse/hse.pyx:929:52: 'bool' is not a constant, variable or function identifier
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    extensions = cythonize(extensions)
  File "setup.py", line 54, in docstring_cythonize
    "warn.multiple_declarators": True,
  File "/usr/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/usr/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: hse/hse.pyx
```

I have also tried to use `bint` for fun, but that also fails. Every other return type annotation seems to work fine. Just `bool` seems to have issues. Note that importing bool from libcpp is also not helpful.

**Comment by da-woods** [comment]
It definitely doesn't understand `Optional`, and I don't think it understand the subscripted `Tuple` container either. If this is a `def` function then the return type isn't used anyway.

I'm not sure exactly why and where it's failing, but the overall annotation you're trying to give isn't going to help Cython.

**Comment by scoder** [comment]
Regardless of whether the declaration is helpful for Cython or not (now or at some point in the future), this is a legitimate Python type annotation and shouldn't fail to compile.

**Comment by da-woods** [comment]
It compiles fine on with both 0.29.21 and 3.0a6. @tristan957, if you want to use annotations it's well worth upgrading Cython since handling them has definitely been improved recently.

**Comment by scoder** [comment]
Right. I hadn't noticed that the version given was 0.28. Thanks for checking.

**Comment by tristan957** [comment]
Hmm ok. I'll look into upgrading. I believe the version I have is just the default for RHEL8. I know the type annotations don't help Cython but to me it's just extra documentation about what a function does. Plus the signature gets added to the docstring which helps self-documenting the function in addition to my stub file.

**Comment by da-woods** [comment]
There's an [annotation_typing](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives) compiler directive if you want Cython to ignore the annotations - it might help if you've got detailed annotations that it can't understand.

I'm not sure what version it was introduced in so you might still have to upgrade though.

**Comment by tristan957** [comment]
Yep I am using that in combination with embedsignature on my project. Hard to tell how useful annotation typing is but I do have it enabled!

**Comment by tristan957** [comment]
@da-woods I have 0.29.21 installed in a virtual environment, but I am getting the same compilation error. I also tried turning `annotation_typing` to False and still received the error. Below are my compiler directives.

```python
compiler_directives={
                "language_level": "3",
                "embedsignature": True,
                "profile": True,
                "infer_types": False,
                "annotation_typing": True,
                "emit_code_comments": True,
                "optimize.use_switch": True,
                "optimize.unpack_method_calls": True,
                "warn.unreachable": True,
                "warn.maybe_uninitialized": True,
                "warn.multiple_declarators": True,
            }
```

Smallest repro

```python
from typing import List

def read() -> bool: #compiles
    pass

def read2() -> List[bool]: #no-compile
    pass
```

Seems to be that bool in a generic position just completely throws off the parser

**Comment by tristan957** [comment]
I did just install Cython 3.0a6 and it worked fine. I'll just move my minimum required Cython version to that and live life on the edge for now.

**Comment by tristan957** [comment]
Ok so in my further exploration of the bool type system support, I have found a new issue in a similar manner.

```python
# x.pyx
from typing import Dict, Union, List

Config = Dict[str, Union[str, int, float, bool, List[str], List[int], "Config"]]
```

The compiler does not love `bool` in the type definition.

Current Cython version is 3.0a6.

**Comment by tristan957** [comment]
Wrapping `bool` in quotes is a current workaround.

**Comment by da-woods** [comment]
> ```python
> # x.pyx
> from typing import Dict, Union, List
> 
> Config = Dict[str, Union[str, int, float, bool, List[str], List[int], "Config"]]
> ```

That example seems to compile fine for me in both 0.29.21 and 3.0a6. I'd double check that you're using the version that you think you are (and it's not finding the lower, system-installed version instead)

**Comment by tristan957** [comment]
I just uninstalled python3-Cython from my machine, re-entered my venv, tried again and received the same error.

`which cython` points to the venv. The stacktrace also points to the venv.

**Comment by tristan957** [comment]
If I literally only have the minimum example above, I get a successful compilation using `cython x.pyx`. If I condense my `pyx` file that is in my project down to the same contents as `x.pyx`, I get the compilation error. I tried without any compiler directives set, and got the same error. Although the code I am working on right now is will be open-sourced, it will be soon. If you think it would be valuable to see the project in it's entirety, I would be more than willing to reach out to the proper channels to get you a tar file of it.

**Comment by da-woods** [comment]
> I would be more than willing to reach out to the proper channels to get you a tar file of it.

I don't think I personally want to investigate this much further right now. I think we know annotations (especially more complex ones) are a bit buggy.

The obvious thing to check for is that you don't have a different definition of `bool` somewhere (e.g. if I add `from libcpp cimport bool` then I can get a compile error; this might be in a pxd file instead). Other than that I don't think I have much to add to this.

**Comment by tristan957** [comment]
yea I do have a `from libcpp import bool` statement in my accompanying `pxd` file. Good to know. Thanks for your help. Will just live with the workaround for now.

**Comment by da-woods** [comment]
If that's the case your best workaround is to do something like `from libcpp import bool as cppbool` and make sure the C++ type and the Python type are clearly distinguished.

**Comment by tristan957** [comment]
Even better tip 👍
