### ISSUE TITLE
Segfault when cythonizing

### ISSUE THREAD

**Issue by wkerzendorf** [cython/cython#2505]
@scoder this looks like the same bug as #2199 . It occurs on OSX with clang using cython 0.28.4:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x00000001000e4608 libpython2.7.dylib`_PyObject_GetDictPtr + 8
    frame #1: 0x0000000103d1e27b Code.so`__Pyx_AddTraceback + 107
    frame #2: 0x0000000103d8b234 Code.so`__pyx_pw_6Cython_8Compiler_4Code_11GlobalState_61lookup_filename + 1924
    frame #3: 0x0000000103d3b80b Code.so`__pyx_pw_6Cython_8Compiler_4Code_11CCodeWriter_205lookup_filename + 379
    frame #4: 0x0000000103d3df31 Code.so`__pyx_pw_6Cython_8Compiler_4Code_11CCodeWriter_195error_goto + 1137
    frame #5: 0x0000000103d3d387 Code.so`__pyx_pw_6Cython_8Compiler_4Code_11CCodeWriter_197error_goto_if + 759
    frame #6: 0x000000010009dc55 libpython2.7.dylib`PyObject_Call + 101
    frame #7: 0x000000010014a168 libpython2.7.dylib`PyEval_EvalFrameEx + 22088
    frame #8: 0x00000001001448c4 libpython2.7.dylib`PyEval_EvalCodeEx + 2164
    frame #9: 0x000000010014ec0d libpython2.7.dylib`fast_function + 109
```

**Comment by scoder** [comment]
Could you please provide the complete stack trace? I double checked the code here and fail to see a way how this can occur with 0.28.4.

**Comment by wkerzendorf** [comment]
okay I checked on TRAVIS the OSX version of Cython
```
Traviss-Mac-463:tardis travis$ source activate tardis
(tardis) Traviss-Mac-463:tardis travis$ python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cython
>>> cython.__path__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__path__'
>>> cython.__version__
'0.28.4'
>>> import Cython
>>> Cython.__version__
'0.28.4'
```

**Comment by wkerzendorf** [comment]
This is starting up lldb
```
(tardis) Traviss-Mac-463:tardis travis$ lldb python
(lldb) target create "python"
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/travis/miniconda/envs/tardis/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/Users/travis/miniconda/envs/tardis/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Current executable set to 'python' (x86_64).
```

**Comment by wkerzendorf** [comment]
@scoder - maybe the version 0.28.4 in the conda-forge osx channel is not 0.28.4 - who is the maintainer of that?

**Comment by wkerzendorf** [comment]
and now it works

**Comment by wkerzendorf** [comment]
@scoder - now I can't even get cython to segfault when running in LLDB in the TRAVIS debug mode. It still segfaults in the Travis build. We will disable OSX builds for now in TRAVIS and see if the next release fixes the issue. I wonder if cython 0.28.4 in OSX-build on conda-forge is maybe not the code version 0.28.4 but an earlier version that is falsely labeled.

**Comment by tomaszmi** [comment]
I'm observing similar issue using cython 0.29.6 version on macOS (Mojave) using the following [cython_test.tar.gz](https://github.com/cython/cython/files/2936471/cython_test.tar.gz) simple "Hello, World" app. The app uses address sanitizer when building the code in the debug mode. How to use it:
```
$ tar xvf cython_test.tar.gz
$ ./build_and_run.sh
........
AddressSanitizer:DEADLYSIGNAL
=================================================================
==33386==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x000103fa1b81 bp 0x7ffeebc5f9a0 sp 0x7ffeebc5f900 T0)
==33386==The signal is caused by a READ memory access.
==33386==Hint: address points to the zero page.
   #0 0x103fa1b80 in call_quack caller.c:1121
   #1 0x103fa1b21 in main main.cpp:12
   #2 0x7fff71a97ed8 in start (libdyld.dylib:x86_64+0x16ed8)
```
Turning sanitizer off:
```
lldb ./quacker
(lldb) target create "./quacker"
Current executable set to './quacker' (x86_64).
(lldb) r
Process 33866 launched: './quacker' (x86_64)
Process 33866 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x18)
    frame #0: 0x0000000100001c31 quacker`call_quack at caller.c:1121
   1118	 * cdef public void call_quack():
   1119	 *     quack()             # <<<<<<<<<<<<<<
   1120	 */
-> 1121	  __Pyx_GetModuleGlobalName(__pyx_t_2, __pyx_n_s_quack); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 6, __pyx_L1_error)
   1122	  __Pyx_GOTREF(__pyx_t_2);
   1123	  __pyx_t_3 = NULL;
   1124	  if (CYTHON_UNPACK_METHODS && unlikely(PyMethod_Check(__pyx_t_2))) {
Target 0: (quacker) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x18)
  * frame #0: 0x0000000100001c31 quacker`call_quack at caller.c:1121
    frame #1: 0x0000000100001be2 quacker`main at main.cpp:12
    frame #2: 0x00007fff71a97ed9 libdyld.dylib`start + 1
    frame #3: 0x00007fff71a97ed9 libdyld.dylib`start + 1
```
Env details:
```
$ python3 --version
Python 3.7.2
$ cython --version
Cython version 0.29.6
$ cc --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$
```

**Comment by wkerzendorf** [comment]
We switched to Python 3 and the problem disappeared. unclear why.

**Comment by tomaszmi** [comment]
Lucky you, however I'm observing the issue using the combination of python3 and cython 0.29.6

**Comment by ermik** [comment]
I have an error trying to run a successfully built script:
```
Traceback (most recent call last):
  File "parse.pyx", line 3, in init parse
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

running 
```sh
INCL=$(python2-config --includes)
cp ./parse.py ./parse.pyx;
cython -2 ./parse.pyx --embed;
gcc -v -Os $INCL -o parse parse.c $(python2-config --libs) -lpthread -lm -lutil -ldl;
```

**Comment by scoder** [comment]
This `ImportError` seems unrelated to the original segfault described in this ticket. It's also unclear if this is related to Cython at all. (And note that you do not need to change the file extension just to compile it with Cython.)

It looks to me like this ticket describes three different issues by now.
- The one by @tomaszmi hints at some kind of Python initialisation problem on user side.
- The `ImportError` in Py2 is probably related to the way Python 2.x initialises extension modules, which is different from Python modules. Use Python 3, or avoid things like circular imports (which should actually best be avoided in any case).
- The original segfault is a duplicate of #2885.

Closing this ticket.

**Comment by tomaszmi** [comment]
> * The one by @tomaszmi hints at some kind of Python initialisation problem on user side.

I'm not sure if the problem was on user side. Definitely the code crashes with cython 0.29 but the same code works works fine with cython 0.27 and 0.28.
