### ISSUE TITLE
Cython-0.29.11 fails to build with Python 3.8.0b2

### ISSUE THREAD

**Issue by cgohlke** [cython/cython#3031]
Ref #3009

`Python 3.8.0b2 (tags/v3.8.0b2:21dd01d, Jul  4 2019, 16:00:09) [MSC v.1916 64 bit (AMD64)] on win32`

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IX:\python38\include -IX:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /TcCython-0.29.11\Cython\Plex\Scanners.c /Fobuild\temp.win-amd64-3.8\Release\Build\Cython\Cython-0.29.11\Cython\Plex\Scanners.obj
Scanners.c
Cython-0.29.11\Cython\Plex\Scanners.c(7244): warning C4003: not enough arguments for function-like macro invocation '__Pyx_PyCode_New'
Cython-0.29.11\Cython\Plex\Scanners.c(7244): warning C4047: 'function': 'int' differs in levels of indirection from 'PyObject *'
Cython-0.29.11\Cython\Plex\Scanners.c(7244): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 6
Cython-0.29.11\Cython\Plex\Scanners.c(7244): warning C4047: 'function': 'PyObject *' differs in levels of indirection from 'int'
Cython-0.29.11\Cython\Plex\Scanners.c(7244): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 14
Cython-0.29.11\Cython\Plex\Scanners.c(7244): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 15
Cython-0.29.11\Cython\Plex\Scanners.c(7244): error C2059: syntax error: ')'
Cython-0.29.11\Cython\Plex\Scanners.c(7256): warning C4003: not enough arguments for function-like macro invocation '__Pyx_PyCode_New'
Cython-0.29.11\Cython\Plex\Scanners.c(7256): warning C4047: 'function': 'int' differs in levels of indirection from 'PyObject *'
Cython-0.29.11\Cython\Plex\Scanners.c(7256): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 6
Cython-0.29.11\Cython\Plex\Scanners.c(7256): warning C4047: 'function': 'PyObject *' differs in levels of indirection from 'int'
Cython-0.29.11\Cython\Plex\Scanners.c(7256): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 14
Cython-0.29.11\Cython\Plex\Scanners.c(7256): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 15
Cython-0.29.11\Cython\Plex\Scanners.c(7256): error C2059: syntax error: ')'
Cython-0.29.11\Cython\Plex\Scanners.c(7268): warning C4003: not enough arguments for function-like macro invocation '__Pyx_PyCode_New'
Cython-0.29.11\Cython\Plex\Scanners.c(7268): warning C4047: 'function': 'int' differs in levels of indirection from 'PyObject *'
Cython-0.29.11\Cython\Plex\Scanners.c(7268): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 6
Cython-0.29.11\Cython\Plex\Scanners.c(7268): warning C4047: 'function': 'PyObject *' differs in levels of indirection from 'int'
Cython-0.29.11\Cython\Plex\Scanners.c(7268): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 14
Cython-0.29.11\Cython\Plex\Scanners.c(7268): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 15
Cython-0.29.11\Cython\Plex\Scanners.c(7268): error C2059: syntax error: ')'
Cython-0.29.11\Cython\Plex\Scanners.c(7280): warning C4003: not enough arguments for function-like macro invocation '__Pyx_PyCode_New'
Cython-0.29.11\Cython\Plex\Scanners.c(7280): warning C4047: 'function': 'int' differs in levels of indirection from 'PyObject *'
Cython-0.29.11\Cython\Plex\Scanners.c(7280): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 6
Cython-0.29.11\Cython\Plex\Scanners.c(7280): warning C4047: 'function': 'PyObject *' differs in levels of indirection from 'int'
Cython-0.29.11\Cython\Plex\Scanners.c(7280): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 14
Cython-0.29.11\Cython\Plex\Scanners.c(7280): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 15
Cython-0.29.11\Cython\Plex\Scanners.c(7280): error C2059: syntax error: ')'
Cython-0.29.11\Cython\Plex\Scanners.c(10057): warning C4003: not enough arguments for function-like macro invocation '__Pyx_PyCode_New'
Cython-0.29.11\Cython\Plex\Scanners.c(10057): warning C4047: 'function': 'int' differs in levels of indirection from 'PyObject *'
Cython-0.29.11\Cython\Plex\Scanners.c(10057): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 6
Cython-0.29.11\Cython\Plex\Scanners.c(10057): warning C4047: 'function': 'PyObject *' differs in levels of indirection from 'int'
Cython-0.29.11\Cython\Plex\Scanners.c(10057): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 14
Cython-0.29.11\Cython\Plex\Scanners.c(10057): warning C4024: 'PyCode_NewWithPosOnlyArgs': different types for formal and actual parameter 15
Cython-0.29.11\Cython\Plex\Scanners.c(10057): error C2059: syntax error: ')'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

**Comment by cgohlke** [comment]
This seems to work with 0.29.x:
```patch
diff --git a/Cython/Utility/ModuleSetupCode.c b/Cython/Utility/ModuleSetupCode.c
index 5df558471..5a582b5ab 100644
--- a/Cython/Utility/ModuleSetupCode.c
+++ b/Cython/Utility/ModuleSetupCode.c
@@ -381,12 +381,9 @@ class __Pyx_FakeReference {
   #define __Pyx_DefaultClassType PyClass_Type
 #else
   #define __Pyx_BUILTIN_MODULE_NAME "builtins"
-#if PY_VERSION_HEX < 0x030800A4
+#if PY_VERSION_HEX < 0x030800A4 || PY_VERSION_HEX >= 0x030800B2
   #define __Pyx_PyCode_New(a, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos) \
           PyCode_New(a, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
-#elif PY_VERSION_HEX >= 0x030800B2
-  #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos) \
-          PyCode_NewWithPosOnlyArgs(a, p, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
 #else
   #define __Pyx_PyCode_New(a, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos) \
           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
```

**Comment by scoder** [comment]
🙄 thanks …
