### ISSUE TITLE
[BUG] Recent regression in Cython development version with fused types seen in scikit-learn CI

### ISSUE THREAD

**Issue by lesteve** [cython/cython#7113]
### Describe the bug

We have seen this in scikit-learn CI this morning (east European time) where we have a daily CI that runs against the development version of our dependencies including Cython, see https://github.com/scikit-learn/scikit-learn/issues/32022.

A git bisect points to c18627cf0c6b933248addc2225ea602d1f58e945, which seems to make sense since the error is about fused types:
```
error: redefinition of ‘__pyx_ff_map_fused_2_000_double__and_float’
```

It could also well be that we are doing some weird things in scikit-learn ...

Looking at the Cython nightly wheel upload ([12 hours ago](https://github.com/cython/cython/actions/runs/17255420129/job/48966141522) and [4 days ago](https://github.com/cython/cython/actions/runs/17182971590/job/48747924851)) it looks like this happens in between these 2 commits:
```
git l af509320cf8f8585d589c757e3bb5ac31006e287...f906608b24b3757897b81fa7feb28be50bf255a8
* f906608b2 - Fix Limited API in api.h files (#7110) (18 hours ago) <da-woods>
* d9ca7d0f2 - Remove timeout and warning from py_thread_type_lock (#7081) (18 hours ago) <da-woods>
* c30852923 - Fix a crash in sys.monitoring (#7063) (18 hours ago) <da-woods>
* ebdfec8c9 - Remove unused scanners code (GH-7049) (19 hours ago) <da-woods>
* fbe126af4 - Fix typo in changelog. (20 hours ago) <Stefan Behnel>
* 2a1993586 - Update changelog. (25 hours ago) <Stefan Behnel>
* 7672ec0b2 - Library: Add declarations for new refcounting C-API functions in Py3.14. (25 hours ago) <Stefan Behnel>
* c18627cf0 - Reduce redundancy in fused type dispatch functions (GH-7100) (2 days ago) <scoder>
* 3f1dcfba3 - Enable one more fstring error test (#7105) (3 days ago) <da-woods>
* c600196f5 - Remove a breakpoint() call that shouldn't be there (#7104) (3 days ago) <da-woods>
```

### Code to reproduce the behaviour:

```bash
git clone https://github.com/scikit-learn/scikit-learn --depth 1
cd scikit-learn
python -m venv .venv
source .venv/bin/activate
pip install meson-python ninja scipy git+https://github.com/cython/cython
pip install . --no-build-isolation -v
# you can also do this to only build one of the problematic file (change name of the file to match Python and OS)
# meson setup build --reconfigure
# ninja -C build sklearn/_loss/_loss.cpython-313-x86_64-linux-gnu.so.p/meson-generated__loss.c.o
```

### Expected behaviour

No error

### OS

Linux

### Python version

3.13

### Cython version

Development version

### Additional context

The source file is actually a [templated file](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/_loss/_loss.pyx.tp) that we use to generate the code with tempita IIRC, so it could well be that scikit-learn is doing some not really supported things

**Comment by da-woods** [comment]
Thanks for the report - you aren't the only ones to experience this so hopefully it can be sorted fairly soon

**Comment by scoder** [comment]
I took the easy way out by including a code hash in the function cnames. The functions and their type dependencies are dynamically generated and it's difficult to collect a complete list of all factors that impact the implementation. Basically, if the implementations or their predeclarations differ, there's probably a reason for that and it's fine to make them different functions.

**Comment by scoder** [comment]
I've triggered a new 'nightly' wheel build to fix this, to be uploaded later today.

**Comment by lesteve** [comment]
Great thanks a lot for the fix!

**Comment by lesteve** [comment]
Just to confirm that the scikit-learn nightly CI using dev dependencies worked fine today 🙏.
