### ISSUE TITLE
[BUG] Undeclared variables with numpy < 2 and cython >= 3.0.9 on Ubuntu Jammy (LTS)

### ISSUE THREAD

**Issue by tfardet** [cython/cython#6257]
### Describe the bug

Trying to compile the cython code via ``python setup.py build`` leads to many errors from undefined variables (full log [here](https://builds.sr.ht/~tfardet/job/1257694#task-setup-2794)):

```
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./nngt/generation -I./nngt/generation/ -I/home/build/.nngt_env/lib/python3.10/site-packages/numpy/core/include -I/home/build/.nngt_env/include -I/usr/include/python3.10 -c ./nngt/generation/cconnect.cpp -o build/temp.linux-x86_64-3.10/./nngt/generation/cconnect.o -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -std=c++14 -Wno-cpp -Wno-unused-function -ffast-math -msse -ftree-vectorize -O2 -g -fopenmp
./nngt/generation/cconnect.cpp: In function ‘npy_intp __pyx_f_5numpy_5dtype_8itemsize_itemsize(PyArray_Descr*)’:
./nngt/generation/cconnect.cpp:20434:13: error: ‘PyDataType_ELSIZE’ was not declared in this scope; did you mean ‘PyDataType_ISUNSIZED’?
20434 |   __pyx_r = PyDataType_ELSIZE(__pyx_v_self);
      |             ^~~~~~~~~~~~~~~~~
      |             PyDataType_ISUNSIZED
./nngt/generation/cconnect.cpp: In function ‘npy_intp __pyx_f_5numpy_5dtype_9alignment_alignment(PyArray_Descr*)’:
./nngt/generation/cconnect.cpp:20468:13: error: ‘PyDataType_ALIGNMENT’ was not declared in this scope; did you mean ‘PyDataType_ISSIGNED’?
...
```

### Code to reproduce the behaviour:

The ``cconect.pyx/pxd`` file are visible [here](https://git.sr.ht/~tfardet/NNGT/tree/numpy2/item/nngt/generation), the only numpy/cython specific thing is the ``cimport numpy as cnp`` and the use of ``cnp.uint8_t``, ``cnp.int64_t`` and ``cnp.ndarray[cnp.int64_t, ndim=1/2]``.
The setup.py is [here](https://git.sr.ht/~tfardet/NNGT/tree/numpy2/item/setup.py).

### Expected behaviour

Compilation [works fine with cython <= 3.0.8](https://builds.sr.ht/~tfardet/job/1257690#task-test).

### OS

Ubuntu Jammy

### Python version

3.10.12

### Cython version

``>= 3.0.9``

### Additional context

Surprisingly enough, compiling the same code works fine locally on my Fedora with python 3.12 and cython 3.0.10.
This is using numpy 1.26.4 in all cases.

**Comment by da-woods** [comment]
I don't think this is a Cython bug. `PyDataType_ELSIZE` and `PyDataType_ALIGNMENT` don't appear in the Cython code at all.

They look to be new in Numpy 2. I think you're somehow using the Numpy pxd files from Numpy 2, but the headers from Numpy 1.something.

**Comment by tfardet** [comment]
@da-woods thanks for the quick reply, what I don't understand is why the error happens only with version 3.0.9 and later, while 3.0.8 compiles fine.
This is the same environment and same numpy, the only thing that changes is the cython version, which seems to point at a change of behavior there.
I'll try to dig in the code to see where that could come from but since I don't know it at all, I was hoping someone from the dev team may know where the issue could come from (at least in terms of which files I should look at).

**Comment by rgommers** [comment]
You are probably installing a numpy 2.0.0 somehow, perhaps due to build isolation or how you manually created your virtualenv. Your `setup.py` has an `import numpy` and then `np.get_include()`. If you check `np.__version__` and `np.__file__` after import, you should be able to deduce whether the version is indeed 2.0 and where it was installed to (and from there, by what tool/command).

**Comment by tfardet** [comment]
@rgommers I will check this out, but I don't understand why this would be a problem with cython > 3.0.8 only...

**Comment by tfardet** [comment]
Re-running the test to check the numpy version (it was indeed 1.26), [the build passed with cython 3.0.10](https://builds.sr.ht/~tfardet/job/1258531), so I've no idea what happened...
I also ran it with cython 3.0.10 and numpy 2 and this passed too.
I'm closing this since it's no longer an issue for me, though I'm afraid it probably won't help anyone who encounters it later on.
