### ISSUE TITLE
Compilation error: lvalue required as unary ‘&’ operand

### ISSUE THREAD

**Issue by ramonz** [cython/cython#2155]
Hi. Compiling the code causes the error: lvalue required as unary ‘&’ operand

run_test.py:
```python
from test import test


test()
```

test.py:
```python
import cython


def test():
    if cython.compiled:
        print("Yep, I'm compiled.")
    else:
        print("Just a lowly interpreted script.")

    a = None
    b = None

    c = (a, b)

    print(c.count(None) in [0, 2])
```

```
➜  ~ /usr/local/lib/python2.7.12/bin/cython -2 -X always_allow_keywords=True -D ./test.py                                                                        
➜  ~ /usr/local/bin/gcc -shared -pthread -pipe -fPIC -fwrapv -Wall -fno-strict-aliasing -O2 -I/usr/local/lib/python2.7.12/include/python2.7 -o ./test.so ./test.c
./test.c: In function ‘__pyx_pf_4test_test’:
./test.c:873:67: error: lvalue required as unary ‘&’ operand
                     (*(__Pyx_PyCFunctionFast)(cfunc)->func)(self, &arg, 1) :\
                                                                   ^
./test.c:1212:15: note: in expansion of macro ‘__Pyx_CallUnboundCMethod1’
   __pyx_t_2 = __Pyx_CallUnboundCMethod1(&__pyx_umethod_PyTuple_Type_count, __pyx_v_c, Py_None); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 15, __pyx_L1_error)
               ^
./test.c:874:79: error: lvalue required as unary ‘&’ operand
                     (*(__Pyx_PyCFunctionFastWithKeywords)(cfunc)->func)(self, &arg, 1, NULL)) :\
                                                                               ^
./test.c:1212:15: note: in expansion of macro ‘__Pyx_CallUnboundCMethod1’
   __pyx_t_2 = __Pyx_CallUnboundCMethod1(&__pyx_umethod_PyTuple_Type_count, __pyx_v_c, Py_None); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 15, __pyx_L1_error)
               ^
./test.c:876:79: error: lvalue required as unary ‘&’ operand
                     (*(__Pyx_PyCFunctionFastWithKeywords)(cfunc)->func)(self, &arg, 1, NULL) :\
                                                                               ^
./test.c:1212:15: note: in expansion of macro ‘__Pyx_CallUnboundCMethod1’
   __pyx_t_2 = __Pyx_CallUnboundCMethod1(&__pyx_umethod_PyTuple_Type_count, __pyx_v_c, Py_None); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 15, __pyx_L1_error)
               ^
```

Next modification solves the problem:
```python
import cython


def test():
    if cython.compiled:
        print("Yep, I'm compiled.")
    else:
        print("Just a lowly interpreted script.")

    a = None
    b = None

    c = (a, b)

    d = None
    print(c.count(d) in [0, 2])
```

```
➜  ~ /usr/local/lib/python2.7.12/bin/cython -2 -X always_allow_keywords=True -D ./test.py                                                                        
➜  ~ /usr/local/bin/gcc -shared -pthread -pipe -fPIC -fwrapv -Wall -fno-strict-aliasing -O2 -I/usr/local/lib/python2.7.12/include/python2.7 -o ./test.so ./test.c
➜  ~ /usr/local/lib/python2.7.12/bin/python2 ./test_run.py                                
Yep, I'm compiled.
True
```

Is this correct behavior or a bug present? Thanks.

```
➜  ~ /usr/local/lib/python2.7.12/bin/cython --version 
Cython version 0.28a0
```

**Comment by scoder** [comment]
This has been fixed in the final release.

**Comment by ramonz** [comment]
Works in 0.28.1
