### PR TITLE
Avoid copying whole with block

### LINKED ISSUE #7122: [BUG] `RecursionError` is hit during cythonization when exceeding certain number of code blocks
### Describe the bug

Trying to compile the generated pseudo code (that mimics actual production code) would hit a `RecursionError`:
```shell
$ cythonize -i -3 mylib.pyx 
Compiling /local/home/leof/dev/recursion_bug/mylib.pyx because it changed.
[1/1] Cythonizing /local/home/leof/dev/recursion_bug/mylib.pyx
Traceback (most recent call last):
  File "/local/home/leof/miniforge3/envs/py312_cu129/bin/cythonize", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Build/Cythonize.py", line 251, in main
    _cython_compile_files(all_paths, options)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Build/Cythonize.py", line 67, in _cython_compile_files
    ext_modules = cythonize(
                  ^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1300, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Main.py", line 615, in compile_single
    return run_pipeline(source, options, full_module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Main.py", line 539, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Pipeline.py", line 398, in run_pipeline
    data = run(phase, data)
           ^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Pipeline.py", line 375, in run
    return phase(data)
           ^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/ModuleNode.py", line 222, in process_implementation
    self.generate_c_code(env, options, result)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/ModuleNode.py", line 516, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 404, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 404, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 2210, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 1969, in generate_function_body
    self.body.generate_execution_code(code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 410, in generate_execution_code
    stat.generate_execution_code(code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 8788, in generate_execution_code
    TryFinallyStatNode.generate_execution_code(self, code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 8478, in generate_execution_code
    self.body.generate_execution_code(code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 410, in generate_execution_code
    stat.generate_execution_code(code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 8016, in generate_execution_code
    self.body.generate_execution_code(code)
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 8505, in generate_execution_code
    fresh_finally_clause().generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/site-packages/Cython/Compiler/Nodes.py", line 8493, in fresh_finally_clause
    node_copy = copy.deepcopy(node)
                ^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^

(...)

  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 253, in _reconstruct
    y = func(*args)
        ^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 252, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
            ^^^^^^^^^^^^^^^^^^^
  File "/local/home/leof/miniforge3/envs/py312_cu129/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```

### Code to reproduce the behaviour:

The problematic Cython code can be generated by this script (also mimicking how our production code is generated):
```python
import sys

def generate_pyx(N):
    lines = []
    lines.append("from libc.stdint cimport intptr_t")
    lines.append("import threading\n")
    lines.append("from somewhere import load_library, get_func\n")
    lines.append("\ncdef object __symbol_lock = threading.Lock()")
    lines.append("cdef bint __py_mod_init = False\n")
    # Symbol pointer declarations
    for i in range(N):
        lines.append(f"cdef void* __ptr_{i} = NULL")
    lines.append("")
    lines.append("cdef int _check_or_init() except -1 nogil:")
    lines.append("    global __py_mod_init")
    lines.append("    if __py_mod_init:")
    lines.append("        return 0\n")
    lines.append("    cdef void* handle = NULL")
    lines.append("    with gil, __symbol_lock:")
    # Per-symbol loading logic
    for i in range(N):
        lines.append(f"        global __ptr_{i}")
        lines.append(f"        __ptr_{i} = <void*><intptr_t>get_func(None, \"func{i}\")")
        lines.append(f"        if __ptr_{i} == NULL:")
        lines.append(f"            if handle == NULL:")
        lines.append(f"                handle = <void*><intptr_t>load_library(\"mylibrary\")")
        lines.append(f"            __ptr_{i} = <void*><intptr_t>get_func(<intptr_t>handle, \"func{i}\")\n")
    lines.append("        __py_mod_init = True")
    lines.append("        return 0")
    return "\n".join(lines)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: python {sys.argv[0]} <N>")
        sys.exit(1)
    N = int(sys.argv[1])
    print(generate_pyx(N))
```

By controlling the number of inner blocks `N`, the error can be reproduced. On my side with Cython 3.0.12, N=64 passed:
```shell
$ python generate_pyx.py 64 > mylib.pyx
$ cythonize -i -3 mylib.pyx 
```
but N=65 failed. We've also tried 3.1.3 and observed the same error (maybe with a slightly different N? I forget.)

### Expected behaviour

Cython should be able to handle trivial code like this (I think!) for arbitrary N.

### OS

Linux

### Python version

3.12.11

### Cython version

3.0.12

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by da-woods**
The whole with block was being copied as part of copying the associated finally block. Override __deepcopy__ to avoid copying it.

Fixes #7122

### CODE REVIEW

**Comment by da-woods** [comment]
This probably needs more thought....

File: Cython/Compiler/Nodes.py [hunk 1]
```diff
@@ -140,6 +140,32 @@ def call(*args, **kwargs):
         return super().__new__(cls, name, bases, attrs)
 
 
+def CopyWithUpTreeRefsMixin(*uptree_refs_attrs):
+    class CopyWithUpTreeRefsMixin:
```
Comment (scoder) [inline Cython/Compiler/Nodes.py]: You don't need to generate a class at runtime for this, just override a class attribute in the subclass to list the attribute names.

**Review by scoder — COMMENTED** [review]
I think I'd avoid clearing the attributes and instead overwrite the entries in the shallow-copied object's `__dict__` with deepcopies if they don't match the excluded attributes.

Essentially this answer here:
https://stackoverflow.com/questions/1500718/how-to-override-the-copy-deepcopy-operations-for-a-python-object/15774013#15774013

File: Cython/Compiler/Nodes.py (hunk 1 above)
Comment (scoder) [reply Cython/Compiler/Nodes.py:144]: BTW, `pos` (and probably some other attributes like the control flow state) can or should generally be excluded from deep-copying, so maybe we could have our own `__deepcopy__` implementation in the `Node` base class? We might even be able to find and exploit rules like "if the attribute refers to a `Node` but is not listed in `child_nodes`, then we could exclude it from the deepcopy by default" – something in that order.

**Comment by scoder** [comment]
BTW, `pos` (and probably some other attributes like the control flow state) can or should generally be excluded from deep-copying, so maybe we could have our own `__deepcopy__` implementation in the `Node` base class? We might even be able to find and exploit rules like "if the attribute refers to a `Node` but is not listed in `child_nodes`, then we could exclude it from the deepcopy by default" – something in that order.

**Comment by da-woods** [comment]
I'm a bit worried that if we introduced a general override in `Note.py` there will be many exceptions to the rule and I'll regret trying to characterise them all.

> BTW, `pos` [...] can or should generally be excluded from deep-copying

`SourceDescriptor` has `__deepcopy__` defined as `return self` so that's seems like it's already been handled and the other two elements are just numbers.

I'll do the `__dict__` change though

File: Cython/Compiler/Nodes.py [hunk 2]
```diff
@@ -140,6 +140,24 @@ def call(*args, **kwargs):
...
+
+        cls = self.__class__
+        result = cls.__new__(cls)
+        for k, v in self.__dict__.items():
+            if k in self.uptree_ref_attrs:
+                # Note that memo being keyed by "id" is a bit of an implementation detail;
+                # the documentation says to treat it as opaque.
+                v = memo.get(id(v), v)
+            setattr(result, k, v)
+        return result
```
Comment (scoder) [inline Cython/Compiler/Nodes.py:158]: Hmm, ok – I know, I linked to the answer that seemed to match my intentions, but didn't actually see the memo part in it. Sure, you're right, if there is a replacement already, then it must be used. And the documentation is clear about about `memo` being opaque. :-/

I guess, either this or your previous code will solve the problem, both being a bit fragile in the sense that they tightly couple with the `deepcopy()` implementation. I don't see a way to avoid that, so I'll leave the choice between the two approaches to you. Sorry for being a bit short-sighted here.

Comment (da-woods) [reply Cython/Compiler/Nodes.py:158]: I've at least checked CPython, PyPy and GraalPython and they all use the same implementation of deepcopy so it should at least work reasonably widely.

I think it'd be possible to come up with an alternative if we have to if it does change in future. But it isn't particularly obvious...

I'll use the current version for now I think.

**Comment by da-woods** [comment]
I'll merge this to 3.2 for now. I'm not sure if it's big enough of an issue to justify going to 3.1.x. 3.1.x should be usable with a higher recursion limit.

**Comment by dalcinl** [comment]
@da-woods This PR broke cythonization of mpi4py, after git bisect, the regression comes from c3594439237fe694021b684e525775fcfb14fc44

Reproducer:

```console
cd /tmp
git clone --depth 1 https://github.com/mpi4py/mpi4py.git
cd mpi4py
cython src/mpi4py/MPI.pyx
````

I'm getting
```console
Traceback (most recent call last):
  File "/home/dalcinl/.local/bin/cython", line 7, in <module>
    sys.exit(setuptools_main())
...
  File "/home/dalcinl/Devel/REPOS/cython/Cython/Compiler/ExprNodes.py", line 3650, in calculate_result_code
    return self.var
           ^^^^^^^^
AttributeError: 'ExcValueNode' object has no attribute 'var'

```
an this exception is triggered by code using a `with` statement in the following function that uses fused types
https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/MPI.src/attrimpl.pxi#L204-L217

EDIT: After `git revert c3594439237fe694021b684e525775fcfb14fc44`, I'm back to normal.
