### PR TITLE
Probably fix freethreading build

### LINKED ISSUE #6387: [BUG] master branch doesn't build on free-threaded Python 3.13.0rc2
### Describe the bug

As of the current tip of the master branch, installing Cython with `pip install .` with Python 3.13t (3.13.rc2) fails as
```
(...)

/private/tmp/gpgi/_cython/Cython/Compiler/Parsing.c:86179:42: error: use of undeclared identifier '__pyx_d'
    if (unlikely(__Pyx_PyDict_GetItemRef(__pyx_d, name, &result) == -1)) PyErr_Clear();
                                         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
```
But it worked last week, so I think this is a regression.
I could bisect it down to #5323 (93be6b83b35860d5aa4d904a5907be36278fdca4)

### Code to reproduce the behaviour:

_No response_

### Expected behaviour

_No response_

### OS

_No response_

### Python version

_No response_

### Cython version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by da-woods**
Fixes #6387

### CODE REVIEW

**Comment by neutrinoceros** [comment]
I confirm that this fixes the problem I was having. Thanks !
