### ISSUE TITLE
Can't print variables on cygdb

### ISSUE THREAD

**Issue by hygorxaraujo** [cython/cython#2699]
When I try to debug some cython code I can't print variables, the following error always occurs:
```bash
(gdb) cy print some_variable
Python Exception <type 'exceptions.AttributeError'> 'PyDictObjectPtr' object has no attribute 'items':
Error occurred in Python: 'PyDictObjectPtr' object has no attribute 'items'
```

I'm also getting this one sometimes (usually after the first one):
```bash
Python Exception <class 'gdb.error'> There is no member named ob_sval.:
Error occurred in Python command: There is no member named ob_sval.
```

To reproduce this I created this [repository](https://github.com/hygorxaraujo/cython_wrapper_example) which has an environment for debug configured with Docker.
Steps to reproduce with the code in the repository:
1. `docker build -t cython_debug .`
2. `docker run -it --name cy_debug --cap-add=SYS_PTRACE --security-opt seccomp=unconfined cython_debug bash`
(now inside the container)
3. `python-dbg setup.py build_ext --inplace`
4. `cygdb`
5. `cy break get_area`
6. `cy run test.py`
7. `cy print self`

**Comment by scoder** [comment]
Cython uses a copy of the `libpython.py` module from CPython, last updated about a year ago. It was adapted to work in Py2.7 and later.
https://github.com/cython/cython/blob/master/Cython/Debugger/libpython.py
Originally copied from:
https://github.com/python/cpython/blob/master/Tools/gdb/libpython.py
There might have been upstream updates since then, and there might be bugs in the way it was adapted. Worth debugging.

**Comment by tonymackinnon** [comment]
This can be fixed by adding adding an items method to `PyDictObjectPtr`:

```
class PyDictObjectPtr(PyObjectPtr):
    """
    Class wrapping a gdb.Value that's a PyDictObject* i.e. a dict instance
    within the process being debugged.
    """
    _typename = 'PyDictObject'

    def iteritems(self):
        '''
        Yields a sequence of (PyObjectPtr key, PyObjectPtr value) pairs,
        analogous to dict.iteritems()
        '''
        keys = self.field('ma_keys')
        values = self.field('ma_values')
        entries, nentries = self._get_entries(keys)
        for i in safe_range(nentries):
            ep = entries[i]
            if long(values):
                pyop_value = PyObjectPtr.from_pyobject_ptr(values[i])
            else:
                pyop_value = PyObjectPtr.from_pyobject_ptr(ep['me_value'])
            if not pyop_value.is_null():
                pyop_key = PyObjectPtr.from_pyobject_ptr(ep['me_key'])
                yield (pyop_key, pyop_value)

    def items(self):
        # for python3 compatibility with libcython.py
        return list(self.iteritems())
```

I can't seem to push a branch with this fix, and since it's a copy of the CPython module it may be that we don't want to modify this file in the Cython project at all.

I'm currently patching this module locally, but it would be great to have this fixed.

**Comment by scoder** [comment]
… except that `.items()` does not return a list in Py3. That would rather be `.viewitems()`.

We can definitely switch to the upstream version (which is Py3-only) after releasing Cython 3.0, i.e. for Cython 3.1 (which will drop Py2 compatibility). Any intermediate fix should do The Right Thing.

**Comment by tonymackinnon** [comment]
I don't think `.viewitems()` exists in Py3, but I could be mistaken. I'm not exactly sure how you would create a view object in this situation.

I don't believe the upstream version is Py3-only, so maybe this should be handled in libcython.py instead?
https://github.com/python/cpython/blob/ed5e29cba500c2336aacdb7c77953f1064235b72/Tools/gdb/libpython.py#L671

**Comment by scoder** [comment]
The upstream version actually uses `.iteritems()` everywhere, not `.items()`. That's probably also the right fix for us then.

I've updated `libpython.py` from CPython for now (c6807afdc375eee181c5e610f28c97d8f2f30aef) and changed the usages in `libcython.py` to `.iteritems()` (139bd745692ec8d68422f0345fef706fde9a5d6a).

**Comment by tonymackinnon** [comment]
great thanks!

**Comment by Volker-Weissmann** [comment]
I can reproduce this bug and it also affects the cy exec command:

> (gdb) cy exec 2+3
> Python Exception <class 'gdb.error'> No frame is currently selected.: 
> Error occurred in Python: No frame is currently selected.
> (gdb)

**Comment by Volker-Weissmann** [comment]
Can't reproduce this bug in the newest version of cython.

**Comment by oersted** [comment]
I am experiencing this exact issue with Cython 0.29.21 and GDB 8.2.

In general, I cannot print any variable with cygdb (cy print <variable>). Let me know what extra details I should provide so you can reproduce it.

**Comment by patrick-nicodemus** [comment]
I also have this issue. 
I am running Cython-0.29.34 with the Ubuntu apt system version of python3, which is Python 3.10.6 (I know the documentation says to run the debugger with Python2 but I am not sure that's up to date?)
As an argument to the debugger I gave a copy of Python 3.10.11 which was built with the debug flag enabled.
I have the problem that 
- `cy locals` always prints nothing and returns without error
- `cy globals` or `cy print x` raises the error
```
Python Exception <class 'AttributeError'>: 'PyDictObjectPtr' object has no attribute 'items'
Error occurred in Python: 'PyDictObjectPtr' object has no attribute 'items'
```

**Comment by astrojuanlu** [comment]
I'd suggest trying to reproduce with Cython 3.0.0b1 released two months ago.

**Comment by patrick-nicodemus** [comment]
I have not had much success with 3.0.0b1 and 3.0.0b2.

With 3.0.0b1, the breakpoints do not match correctly to the functions in my code. I put in one function name and the code stops at another. After I do "cy step" twice, the debugger crashes with the following error:
```
Traceback (most recent call last):
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libpython.py", line 1980, in wrapper
    return function(*args, **kwargs)
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libcython.py", line 950, in invoke
    self.step(stepinto=self.stepinto)
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libpython.py", line 2417, in step
    lineno = self.lang_info.lineno(newframe)
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libcython.py", line 898, in lineno
    return self.get_cython_lineno(frame)[1]
TypeError: 'int' object is not subscriptable
Python Exception <class 'TypeError'>: 'int' object is not subscriptable
Error occurred in Python: 'int' object is not subscriptable
``
Cython 3.0.0b2 hits an error as soon as the breakpoint is triggered.
The line number it gives for the breakpoint also corresponds to the wrong function (the same incorrect function as before)
```
Traceback (most recent call last):
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libpython.py", line 1980, in wrapper
    return function(*args, **kwargs)
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libpython.py", line 2427, in run
    self.finish_executing(gdb.execute('run ' + args, to_string=True))
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libpython.py", line 2295, in finish_executing
    source_line = self.lang_info.get_source_line(frame)
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libcython.py", line 903, in get_source_line
    line = super(CythonInfo, self).get_source_line(frame)
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libcython.py", line 83, in wrapper
    return function(self, frame, *args, **kwargs)
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libcython.py", line 273, in get_source_line
    source_desc, lineno = self.get_source_desc()
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libcython.py", line 83, in wrapper
    return function(self, frame, *args, **kwargs)
  File "/home/patn/.local/lib/python3.10/site-packages/Cython/Debugger/libcython.py", line 242, in get_source_desc
    assert filename == filename_and_lineno[0]
TypeError: 'int' object is not subscriptable
Python Exception <class 'TypeError'>: 'int' object is not subscriptable
Error occurred in Python: 'int' object is not subscriptable
```
I will be happy to provide more details.

**Comment by scoder** [comment]
Note that this ticket was closed as fixed in 2020, so please don't use it for unrelated discussions.

There is a PR that overhauls the debugger in some corners. It would help to get feedback on that (and also help to get it finished). Please try the branch and comment on the PR whether this works better for you.

https://github.com/cython/cython/pull/5186
