### PR TITLE
Use std::isfinite() is C++ and isfinite() in C.

### LINKED ISSUE #7915: [BUG] 3.3.0: breaks lap 0.5.13: error: 'isfinite' was not declared in this scope; did you mean 'std::isfinite'?
### Describe the bug

After updating cython in pkgsrc to 3.3.0, the build of lap 0.5.13 started failing with:
```
building 'lap._lapjv' extension
c++ -O2 -g -fstack-clash-protection -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -g -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -fPIC -I_lapjv_cpp -I/usr/pkg/lib/python3.14/site-packages/numpy/_core/include -Ilap -I/usr/pkg/include/python3.14 -c _lapjv_cpp/_lapjv.cpp -o build/temp.netbsd-11.99.7-amd64-cpython-314/_lapjv_cpp/_lapjv.o
_lapjv_cpp/_lapjv.cpp: In function 'int __Pyx_PyObject_CompareFloatIntBoolLt(PyObject*, PyObject*)':
_lapjv_cpp/_lapjv.cpp:12251:19: error: 'isfinite' was not declared in this scope; did you mean 'std::isfinite'?
12251 |     if (unlikely(!isfinite(float_op1))) {
      |                   ^~~~~~~~
_lapjv_cpp/_lapjv.cpp:1504:43: note: in definition of macro 'unlikely'
 1504 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
In file included from /usr/include/g++/complex:44,
                 from _lapjv_cpp/_lapjv.cpp:1544:
/usr/include/g++/cmath:1142:5: note: 'std::isfinite' declared here
 1142 |     isfinite(_Tp)
      |     ^~~~~~~~
error: Command '['c++', '-O2', '-g', '-fstack-clash-protection', '-I/usr/pkg/include', '-I/usr/include', '-I/usr/pkg/include/python3.14', '-g', '-I/usr/pkg/include', '-I/usr/include', '-I/usr/pkg/include/python3.14', '-fPIC', '-I_lapjv_cpp', '-I/usr/pkg/lib/python3.14/site-packages/numpy/_core/include', '-Ilap', '-I/usr/pkg/include/python3.14', '-c', '_lapjv_cpp/_lapjv.cpp', '-o', 'build/temp.netbsd-11.99.7-amd64-cpython-314/_lapjv_cpp/_lapjv.o']' returned non-zero exit status 1.
```

### Code to reproduce the behaviour:

Try building the 0.5.13 release of https://github.com/gatagat/lap using the pypi distfile.

### Expected behaviour

Build succeeds.

### OS

NetBSD

### Python version

3.14.7

### Cython version

3.3.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scoder**
Closes https://github.com/cython/cython/issues/7915

### CODE REVIEW

File: Cython/Utility/ModuleSetupCode.c [hunk 1]
```diff
@@ -1642,6 +1642,14 @@ static CYTHON_INLINE int __Pyx_IsAnySubtype2(PyTypeObject *cls, PyTypeObject *a,
 #define __Pyx_truncl truncl
 #endif
 
+#if defined(__cplusplus)
+  #include <cmath.h>
```
Comment (0-wiz-0) [inline Cython/Utility/ModuleSetupCode.c]: cmath, not cmath.h

**Comment by 0-wiz-0** [comment]
Thank you, @scoder , this fixes #7915 for me!

**Comment by da-woods** [comment]
It obviously works and is fine (at the cost of an extra header in c++ mode) so we should merge this to work around the issue.

It'd be good if @0-wiz-0 could make a netbsd bug report about `<cmath>` hiding the definitions in `<math.h>` since I'm fairly sure it's their defect rather than ours.

**Comment by 0-wiz-0** [comment]
I've [started a discussion](https://mail-index.netbsd.org/tech-toolchain/2026/08/25/msg004887.html) about this.
