### ISSUE TITLE
[BUG] Since 3.3.0, annotating a module level global with `typing.Final` crashes the compiler when declared in pxd

### ISSUE THREAD

**Issue by bdraco** [cython/cython#7942]
### Describe the bug

Since 3.3.0, annotating a module level global with `typing.Final` crashes the compiler when the same name is also declared in the module's `.pxd`. 

The crash is in the new code that checks global annotations against the `.pxd` declaration (added for #7877). `analyse_as_type()` returns `None` for `Final[...]` because Cython does not know `typing.Final`, and the result is used without a `None` check:

```
finalmod.py:3:0: Compiler crash in AnalyseDeclarationsTransform
...
File 'ExprNodes.py', line 2377, in _analyse_target_declaration: NameNode(finalmod.py:3:0,
    name = 'LIMIT',
    ...)

Compiler crash traceback from this point on:
  File ".../Cython/Compiler/ExprNodes.py", line 2377, in _analyse_target_declaration
    if not (annotation_type.assignable_from(entry_type) or entry_type.assignable_from(annotation_type)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'assignable_from'
```

Bare `Final` and a string annotation `"Final[int]"` crash the same way. 

The same annotation on a global that is not in the `.pxd` compiles fine, and the same file compiles fine with 3.2.x, where global annotations were ignored.

### Code to reproduce the behaviour:

`finalmod.py`

```cython
from typing import Final

LIMIT: Final[int] = 128


def bump(x: int) -> int:
    return x + LIMIT
```

`finalmod.pxd`

```cython
cdef unsigned int LIMIT
```

```
cython -3 finalmod.py
```

### Expected behaviour

The file compiles, as it does with 3.2.x. `Final` is only a hint for static type checkers and should not affect the generated code. 

### OS

macOS 15

### Python version

3.14.2

### Cython version

3.3.0

### Additional context

Found while bumping Cython in `aiohttp`, which compiles a pure Python websocket reader with a `.pxd` for the C typing. 

We had to drop `Final` from several module constants to get 3.3.0 to compile the module (aio-libs/aiohttp#13521, aio-libs/aiohttp#13547).

**Comment by matusvalo** [comment]
I bisected the issue and it seems there are **2 issues** in reality:

1. In commit 1f6db306c4134a8cd8cba4225a2b19c56acbf705 the code started producing compilation error:
   ```
   Error compiling Cython file:
   ------------------------------------------------------------
   ...
   from typing import Final
   
   LIMIT: Final[int] = 128
   ^
   ------------------------------------------------------------
   finalmod.py:3:0: 'LIMIT' redeclared
   ```
2. Later in commit 3ee3f71606b4db347bcd204e9e4a851953699fdb the crash was introduced.
