### ISSUE TITLE
Python 3.4 & undefined reference to `_PyGen_Send'

### ISSUE THREAD

**Issue by KeyWeeUsr** [cython/cython#1968]
* GCC from `mingwpy-0.1.0b3`
* Python `3.4.4`
* Cython `0.27.2`

I think it was introduced in `0.27`, our build reports the issue for Python 3.4 versions. See this commit - https://github.com/cython/cython/commit/72acc2cdcbb6fd738fcffe7d193bfc44aefc6474 and https://github.com/cython/cython/blob/94acc16165949becb94ad900c01c63fa1ae80368/Cython/Utility/Coroutine.c#L787

Also notice 3.3+ referenced here and not in the rest of the lines:
https://github.com/cython/cython/blob/94acc16165949becb94ad900c01c63fa1ae80368/Cython/Utility/Coroutine.c#L786

[`build`](https://ci.appveyor.com/project/KivyOrg/kivy/build/1.0.1757/job/3wgpdb8a94cssbh2#L496) ↓

```
writing build\temp.win32-3.4\Release\kivy\_event.def
C:\Python34\Scripts\gcc.exe -shared -s build\temp.win32-3.4\Release\kivy\_event.o build\temp.win32-3.4\Release\kivy\_event.def -LC:\Python34\libs -LC:\Python34\libs -LC:\Python34\PCbuild -lpython34 -lmsvcr100 -o C:\projects\kivy\kivy\_event.pyd -lm
build
\temp.win32-3.4\Release\kivy\_event.o:_event.c:(.text+0x45da): undefined reference to `_PyGen_Send'
build\temp.win32-3.4\Release\kivy\_event.o:_event.c:(.text+0x9290): undefined reference to `_PyGen_Send
'
collect2.exe: error: ld returned 1 exit status
 error: command 'C:\\Python34\\Scripts\\gcc.exe' failed with exit status 1
Failed with exit code 1
```

The file [`_event.pxd`](https://github.com/kivy/kivy/blob/master/kivy/_event.pxd) hasn't changed for quite a while + the build worked fine with `<0.27`.

Any ideas how to fix it without downgrading to 0.26?

**Comment by scoder** [comment]
MinGW probably doesn't set `_MSC_VER` (because, why should it?), so the guard doesn't apply and opens up the special case for Python < 3.6. Problem is, it shouldn't guard against MSVC since this is a plarform issue, not a compiler thing. The `_PyGen_Send()` function is not properly exported before https://github.com/python/cpython/commit/833c626, and the fact that Linux systems do not care is not a good excuse for blaming it on Windows (let alone MSVC, although that is always a good target for blaming). I'll change the guard to `defined(__linux__)` for 0.27.3.

**Comment by KeyWeeUsr** [comment]
@scoder Thanks for such a quick response and for the fix! :) Any ETA for `0.27.3`?
