### PR TITLE
Fixing cygdb

### PR DESCRIPTION
**Pull request by Volker-Weissmann**
As you might know, cygdb is currently in an unusable state.
Many tests that can be executed by running `python TestLibCython.py` don't pass.

The "cy print"  command was broken, so I replaced it with this code:
`self.cy.exec_.invoke("print(" + name + ")", from_tty)`
The main advantage of this code is that it reduces the complexity and code size of Cygdb.
Another advantage is that it can use `__repr__` functions and is therefore consistent with pdb.
The disadvantage is that `cy print *var` no longer works, but I think you should use `cy_cname` and gdb's `print` function instead. I'm going to update the documentation about this.
This was when I found out that `cy exec` is also broken, it can't read local variables.
This bug is the only thing seperating a nearly unusable cygdb from a cygdb that passes all tests.

Fixing this bug is beyond my Cython-knowledge, so I will ask on the mailing list with additional details about this bug.

### CODE REVIEW

File: Cython/Compiler/ModuleNode.py [hunk 1]
```diff
@@ -3082,6 +3082,14 @@ def mod_init_func_cname(self, prefix, env):
         # from PEP483
         return self.punycode_module_name(prefix, env.module_name)
 
+    # Returns the name of the C-function that corresponds to the module initialisation.
+    # (module initialisation == the cython code outside of functions)
+    # Note that this should never be the name of a wrapper and always the name of the
+    # function containing the actual code. Otherwise, cygdb will experience problems.
+    def module_init_func_cname(self):
```
Comment (scoder) [inline Cython/Compiler/ModuleNode.py:3089]: For consistency with the other methods, I would still pass `env` as argument here.
Also, this is the "module exec" function, not the "module init" function (since PEP-489).
In fact, the name of the function (exec or init) that populates the module namespace depends on whether PEP-489 is used or not, which is a C compile time setting.
I guess we could unify that by always creating the exec function and passing it the module object in the non-PEP489 case, but that would be a separate PR.
In any case, PEP-489 is the default way to init a module now.

File: Cython/Compiler/Code.py [hunk 2]
```diff
@@ -1798,14 +1799,23 @@ def getvalue(self):
...
-        cython_lineno = self.last_marked_pos[1] if self.last_marked_pos else 0
+        # Cygdb needs to know which Cython source line corresponds to which C line.
+        # Therefore, we write the information which Cython line corresponds to which
+        # C line into self.buffer.markers and then write it from there into
+        # cython_debug/cython_debug_info_* (see ModuleNode._serialize_lineno_map).
+        # C lines with cython_lineno = 0 will get ingored by ModuleNode._serialize_lineno_map.
+        # The self.last_marked_pos[0] == self.source_desc check is necessary, because Cygdb
+        # assumes this to be true.
+        if self.last_marked_pos and self.last_marked_pos[0] == self.source_desc:
+            cython_lineno = self.last_marked_pos[1]
```
Comment (scoder) [inline Cython/Compiler/Code.py:1810]: Hmm … this doesn't feel great. I mean, we know the source file that we are currently generating code for. We write the name into the C file as a comment whenever a line starts. There doesn't seem to be a need to pass the source descriptor into the code writer's constructor, and in fact, it's even wrong, because it can generate code for an arbitrary number of source files (py/pyx, pxi, pxd) into the same C file.

I think this decision should solely depend on `last_marked_pos`.

File: Cython/Debugger/libcython.py [hunk 3]
```diff
@@ -1218,7 +1222,11 @@ def _fill_locals_dict(self, executor, local_dict_pointer):
         "Fill a remotely allocated dict with values from the Cython C stack"
         cython_func = self.get_cython_function()
 
-        for name, cyvar in cython_func.locals.iteritems():
+        if sys.version_info[0] == 2:
+            iterator = cython_func.locals.iteritems()
+        else:
+            iterator = cython_func.locals.items()
```
[the remark this answers is not in the document]
Comment (da-woods) [reply Cython/Debugger/libcython.py:1228]: Or just use `items()`?

File: Cython/Debugger/Tests/test_libcython_in_gdb.py [hunk 4]
```diff
@@ -177,12 +177,13 @@ def test_break_lineno(self):
...
 
 
-class TestKilled(DebugTestCase):
-
-    def test_abort(self):
-        gdb.execute("set args -c 'import os; os.abort()'")
-        output = gdb.execute('cy run', to_string=True)
-        assert 'abort' in output.lower()
+# I removed this testcase, because it will never work, because
+# gdb.execute(..., to_string=True) does not capture stdout and stderr of python.
```
[the remark this answers is not in the document]
Comment (Volker-Weissmann) [reply Cython/Debugger/Tests/test_libcython_in_gdb.py:181]: I don't know. I'm not even sure it ever worked.
Lines 2102-2155 in libpython.py are interesting though. The comment says "Have it properly capture stderr also" which is what is needed to make this work.

File: Cython/Debugger/Tests/test_libcython_in_gdb.py [hunk 5]
```diff
@@ -362,6 +403,7 @@ def test_cython_exec(self):
         # test normal behaviour
         self.assertEqual("[0]", self.eval_command('[a]'))
 
+        return #The test after this return freezes gdb, so I temporarily removed it.
```
[the remark this answers is not in the document]
Comment (Volker-Weissmann) [reply Cython/Debugger/Tests/test_libcython_in_gdb.py:406]: Oh, I forgot about that one.
Making this test work is not a bugfix, it would be a feature request. And one that probably involves the modification of not only cygdb's but gdb's source code.
I think we should delete this test or create a feature request issue.
If you ask me, this feature is not worth the work, because you can just use cy exec firstline;secondline or cy exec exec("firstline\nsecondline") or cy exec import fileWithTheLines
Just deleting the test is probably the best idea.

File: Cython/Debugger/libcython.py (hunk 3 above)
[the remark this answers is not in the document]
Comment (Volker-Weissmann) [reply Cython/Debugger/libcython.py]: Using `items()` is probably the simplest solution. See commit ffc07ea
Maybe` items()` is slower that `iteritems()`, but I don't really care about Python 2 performance.

File: Cython/Compiler/ModuleNode.py (hunk 1 above)
Comment (Volker-Weissmann) [reply Cython/Compiler/ModuleNode.py:3089]: We call module_init_func_cname in ParseTreeTransforms.py. There is no `env` variable there, so we would have to use `node.module_init_func_cname(node.scope)`. This doesn't look good to me. I would suggest renaming the function to module_exec_func_cname and not changing anything else.
Maybe we should have tests for both the PEP-489 and the non-PEP-489 case.
What's the reason why Cython supports both using PEP-489 and not using it?

File: Cython/Compiler/Code.py (hunk 2 above)
Comment (Volker-Weissmann) [reply Cython/Compiler/Code.py:1810]: The reason why the old version didn't work is that if you would call `cy break mymodule:123` it would break once it hits line 123 in **any** cython file. I think the best solution would be to undo my chagnes and not only write self.last_marked_pos[1] into the file, but also self.last_marked_pos[0].

Comment (scoder) [reply Cython/Compiler/Code.py:1810]: Sounds like the right thing to do, yes.

File: Cython/Compiler/ModuleNode.py (hunk 1 above)
Comment (scoder) [reply Cython/Compiler/ModuleNode.py:3089]: > Maybe we should have tests for both the PEP-489 and the non-PEP-489 case.

In this case, yes. In general, I think it's ok if it comes implicitly with the Python version.

> What's the reason why Cython supports both using PEP-489 and not using it?

I guess we may remove the non-PEP-489 fallback at some point, but as long as Cython's support for it is not complete (including module reloading and subinterpreters), and as long as we support Python 2.7, it's better to give users a chance to disable this if it ever gets in the way. Second best answer: because we can. :)

> renaming the function to module_exec_func_cname and not changing anything else.

Except that it's currently more than one function name that you're interested in here.

**Comment by Volker-Weissmann** [comment]
All cygdb tests pass now. Cygdb is still far from being good, but its better than before.
I think you can merge this now.

**Comment by oersted** [comment]
Do the tests pass? I am working with Cython 0.29.21 and both `cy print` (#2699) #and `cy exec` seem fully broken. Might it be an issue with my environment? I am running a clean Python 3.8 conda env with GDB 8.2.

```
(gdb) cy print min_kh
Python Exception <class 'AttributeError'> 'PyDictObjectPtr' object has no attribute 'items': 
Error occurred in Python command: 'PyDictObjectPtr' object has no attribute 'items'
```

```
(gdb) cy exec 1 + 1

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
insertdict (value=0x0, hash=-5231208992575627286, Python Exception <class 'RuntimeError'> Type does not have a target.: 
key=, mp=0x7fff90894b40)
    at /tmp/build/80754af9/python_1593706424329/work/Objects/dictobject.c:1034
1034	in /tmp/build/80754af9/python_1593706424329/work/Objects/dictobject.c
Python Exception <class 'gdb.error'> The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(PyDict_SetItem) will be abandoned.
When the function is done executing, GDB will silently stop.: 
Error occurred in Python command: The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(PyDict_SetItem) will be abandoned.
When the function is done executing, GDB will silently stop.
```

File: Cython/Debugger/libcython.py [hunk 6]
```diff
@@ -1111,8 +1107,28 @@ class CyPrint(CythonCommand):
...
+            value = global_python_dict[name].get_truncated_repr(libpython.MAX_OUTPUT_LEN)
+            print('%s = %s' % (name, value))
+            #This also would work, but beacause the output of cy exec is not captured in gdb.execute, TestPrint would fail
+            #self.cy.exec_.invoke("print('"+name+"','=', type(" + name + "), "+name+", flush=True )", from_tty)
+        elif name in module_globals:
+            cname = module_globals[name].cname
+            try:
+                value = gdb.parse_and_eval(cname)
+            except RuntimeError:
+                print("unable to get value of ", name)
```
Comment (scoder) [inline Cython/Debugger/libcython.py:1125]:
```suggestion
                print("unable to get value of %s" % name)
```

File: Cython/Debugger/libcython.py [hunk 7]
```diff
@@ -1111,8 +1107,28 @@ class CyPrint(CythonCommand):
...
+            else:
+                if not value.is_optimized_out:
+                    self.print_gdb_value(name, value)
+                else:
+                    print(name, "is optimized out")
```
Comment (scoder) [inline Cython/Debugger/libcython.py:1130]:
```suggestion
                    print("%s is optimized out" % name)
```

File: Cython/Debugger/libpython.py [hunk 8]
```diff
@@ -1950,22 +1948,13 @@ def invoke(self, args, from_tty):
...
-            for name, pyop_value in namespace:
-                value = pyop_value.get_truncated_repr(MAX_OUTPUT_LEN)
-                print('%-*s = %s' % (max_name_length, name, value))
-
-    def get_namespace(self, pyop_frame):
-        return pyop_frame.iter_locals()
+        for pyop_name, pyop_value in pyop_frame.iter_locals():
+            print('%s = %s'
+                   % (pyop_name.proxyval(set()),
+                      pyop_value.get_truncated_repr(MAX_OUTPUT_LEN)))
```
Comment (scoder) [inline Cython/Debugger/libpython.py:1957]:
```suggestion
            print('%s = %s' % (
                pyop_name.proxyval(set()),
                pyop_value.get_truncated_repr(MAX_OUTPUT_LEN),
            ))
```

File: runtests.py [hunk 9]
```diff
@@ -827,7 +827,7 @@ class CythonCompileTestCase(unittest.TestCase):
     def __init__(self, test_directory, workdir, module, tags, language='c', preparse='id',
                  expect_errors=False, expect_warnings=False, annotate=False, cleanup_workdir=True,
                  cleanup_sharedlibs=True, cleanup_failures=True, cython_only=False, doctest_selector=None,
-                 fork=True, language_level=2, warning_errors=False,
+                 fork=True, language_level=3, warning_errors=False,
```
Comment (scoder) [inline runtests.py:830]: Unrelated change?

File: Cython/Compiler/ModuleNode.py [hunk 10]
```diff
@@ -399,7 +399,7 @@ def generate_c_code(self, env, options, result):
 
         if Options.annotate or options.annotate:
             show_entire_c_code = Options.annotate == "fullc" or options.annotate == "fullc"
-            rootwriter = Annotate.AnnotationCCodeWriter(show_entire_c_code=show_entire_c_code)
+            rootwriter = Annotate.AnnotationCCodeWriter(show_entire_c_code=show_entire_c_code, source_desc=self.compilation_source.source_desc)
```
Comment (scoder) [inline Cython/Compiler/ModuleNode.py:402]:
```suggestion
            rootwriter = Annotate.AnnotationCCodeWriter(
                show_entire_c_code=show_entire_c_code,
                source_desc=self.compilation_source.source_desc,
            )
```

File: Cython/Compiler/ModuleNode.py [hunk 11]
```diff
@@ -528,16 +528,19 @@ def _serialize_lineno_map(self, env, ccodewriter):
...
 
         d = defaultdict(list)
-        for c_lineno, cython_lineno in enumerate(markers):
-            if cython_lineno > 0:
-                d[cython_lineno].append(c_lineno + 1)
+        for c_lineno, cython_tup in enumerate(markers):
+            cython_fp = cython_tup[0]
+            cython_lineno = cython_tup[1]
+            if cython_lineno > 0 and cython_fp.filename is not None:
+                d[cython_fp, cython_lineno].append(c_lineno + 1)
```
Comment (scoder) [inline Cython/Compiler/ModuleNode.py:535]:
```suggestion
        for c_lineno, (src_desc, src_lineno) in enumerate(markers):
            if src_lineno > 0 and src_desc.filename is not None:
                d[(src_desc.filename, src_lineno)].append(c_lineno + 1)
```
and then adapt the code below accordingly. `cython_fp` doesn't seem a very clear name to me.

File: Cython/Compiler/Code.py [hunk 12]
```diff
@@ -1818,10 +1818,19 @@ def getvalue(self):
...
+        # C line into self.buffer.markers and then write it from there into
+        # cython_debug/cython_debug_info_* (see ModuleNode._serialize_lineno_map).
+
+        if self.last_marked_pos:
+            cython_path = self.last_marked_pos[0]
+            cython_lineno = self.last_marked_pos[1]
+        else:
+            cython_path = None
+            cython_lineno = 0
+        self.buffer.markers.extend([(cython_path, cython_lineno)] * s.count('\n'))
```
Comment (scoder) [inline Cython/Compiler/Code.py:1832]:
```suggestion
        # Cygdb needs to know which Cython source line corresponds to which C line.
        # Therefore, we write this information into "self.buffer.markers" and then write it from there
        # into cython_debug/cython_debug_info_* (see ModuleNode._serialize_lineno_map).

        filename_line = self.last_marked_pos[:2] if self.last_marked_pos else (None, 0)
        self.buffer.markers.extend([filename_line] * s.count('\n'))
```

**Comment by scoder** [comment]
@oersted this change is currently scheduled for Cython 3.0. We'll see about 0.29.x at some point.

**Comment by oersted** [comment]
@scoder Thank you for the quick response :+1: 

Is this fix already included in the alpha releases or is it still pending then? Where should I follow for progress updates? I don't see a 3.0 tag in this issue, I assume it is tracked somewhere else?

**Comment by scoder** [comment]
> I don't see a 3.0 tag in this issue, I assume it is tracked somewhere else?

It used to be tracked in my head, but I added the tag now. I'm not saying that it won't be backported (it fixes serious problems, after all), but that's to be decided when it's done and tested.

> Is this fix already included in the alpha releases or is it still pending then?

It's not merged yet. Needs more work and testing. You can help to get it ready faster.

File: Cython/Compiler/Code.py (hunk 12 above)
Comment (scoder) [reply Cython/Compiler/Code.py:1832]: BTW, is it actually correct/good to reuse the same line number for all lines here?

**Comment by oersted** [comment]
Alright, good, thank you. I would help out if it were critical for my current work, but I can mostly cover my bases with classical print-debugging and the backtrace functionality of cygdb seems to work well to diagnose hard crashes. In any case, I am not too familiar with the internals of Cython or GDB's Python interface, so it would take me a while to understand enough to make a proper contribution.

**Comment by scoder** [comment]
> I am not too familiar with the internals of Cython or GDB's Python interface

No problem. You don't need to know much about Cython here, and working with GDB's Python bindings is a lot of trial and error for everyone. Contributions welcome.

**Comment by Volker-Weissmann** [comment]
> Alright, good, thank you. I would help out if it were critical for my current work, but I can mostly cover my bases with classical print-debugging and the backtrace functionality of cygdb seems to work well to diagnose hard crashes. In any case, I am not too familiar with the internals of Cython or GDB's Python interface, so it would take me a while to understand enough to make a proper contribution.

Don't worry I also have no idea what I'm doing.
The problem with print debugging is that you need to recompile it, which can take a few minutes.

**Comment by Volker-Weissmann** [comment]
I think I fixed everything that someone complained about. Should be ready for merging.

File: Cython/StringIOTree.py [hunk 13]
```diff
@@ -107,3 +107,32 @@ def insertion_point(self):
...
+        from collections import defaultdict
+        markers = self.allmarkers()
+        d = defaultdict(list)
+        for c_lineno, cython_lineno in enumerate(markers):
+            if cython_lineno > 0:
+                d[cython_lineno].append(c_lineno + 1)
+        if len(d) == 0:
+            print("allmarkers is empty")
+        for cython_lineno, c_linenos in sorted(d.items()):
+            sys.stdout.write("cython line", cython_lineno, "maps to ")
```
Comment (scoder) [inline Cython/StringIOTree.py:127]: This doesn't work (and is obviously untested). `write()` only takes a single argument. You have to build the output string first. In fact, I'd build a list of line numbers first and then output it in the end. That avoids timing issues with potentially concurrent output.

File: docs/src/userguide/debugging.rst [hunk 14]
```diff
@@ -21,6 +21,8 @@ source, and then running::
     make
     sudo make install
 
+Installing the Cython debugger can be quite tricky. `This installation script and example code <https://gitlab.com/volkerweissmann/cygdb_installation>`_ might be useful.
```
Comment (scoder) [inline docs/src/userguide/debugging.rst:24]: Are you really asking users to build their own gdb package here? After your changes, the system supplied one should just work, no?

**Comment by scoder** [comment]
> This is exactly what I did

Ah, sorry, it's been a while and I forgot that you updated `libpython.py` to the CPython version. So the refactoring there is perfectly ok.

File: Cython/Debugger/libpython.py [hunk 15]
```diff
@@ -1977,24 +1966,80 @@ def get_namespace(self, pyop_frame):
...
 
     def get_namespace(self, pyop_frame):
         return pyop_frame.iter_globals()
 
 
-PyGlobals("py-globals")
+PyGlobals()
 
+# This function used to be a part of CPython's libpython.py (as a member function of frame).
+# It is'nt anymore, so I copied it.
```
Comment (scoder) [inline Cython/Debugger/libpython.py:2021]:
```suggestion
# It isn't anymore, so I copied it.
```

File: Cython/Debugger/libcython.py [hunk 16]
```diff
@@ -859,14 +850,14 @@ def invoke(self, function_names, from_tty):
...
         # Filter init-module functions (breakpoints can be set using
         # modulename:linenumber).
-        names =  [n for n, L in self.cy.functions_by_name.iteritems()
-                        if any(not f.is_initmodule_function for f in L)]
-        qnames = [n for n, f in self.cy.functions_by_qualified_name.iteritems()
-                        if not f.is_initmodule_function]
+        names =  [n for n, L in self.cy.functions_by_name.items()
+                    if any(not f.is_initmodule_function for f in L)]
+        qnames = [n for n, f in self.cy.functions_by_qualified_name.items()
+                    if not f.is_initmodule_function]
```
Comment (scoder) [inline Cython/Debugger/libcython.py:860]:
```suggestion
        names =  [n for n, L in self.cy.functions_by_name.items()
                  if any(not f.is_initmodule_function for f in L)]
        qnames = [n for n, f in self.cy.functions_by_qualified_name.items()
                  if not f.is_initmodule_function]
```

File: Cython/Debugger/Tests/test_libcython_in_gdb.py [hunk 17]
```diff
@@ -322,6 +323,58 @@ def test_print(self):
...
+     7    import os
+     8
+     9    cdef int c_var = 12
+>   10    python_var = 13
+    11
+    12    def spam(a=0):
+    13        cdef:
+    14            int b, c
+'''
+class TestList(DebugTestCase):
```
Comment (scoder) [inline Cython/Debugger/Tests/test_libcython_in_gdb.py:355]:
```suggestion


class TestList(DebugTestCase):
```

File: Cython/Debugger/Tests/test_libcython_in_gdb.py [hunk 18]
```diff
@@ -322,6 +323,58 @@ def test_print(self):
...
+    def workaround_for_coding_style_checker(self, correct_result_wrong_whitespace):
+        correct_result = ""
+        for line in correct_result_test_list_inside_func.split("\n"):
+            if len(line) < 10 and len(line) > 0:
+                line += " "*4
+            correct_result += line + "\n"
+        correct_result = correct_result[:-1]
+    def test_list_inside_func(self):
```
Comment (scoder) [inline Cython/Debugger/Tests/test_libcython_in_gdb.py:363]:
```suggestion

    def test_list_inside_func(self):
```

File: Cython/Compiler/ParseTreeTransforms.py [hunk 19]
```diff
@@ -3466,9 +3466,16 @@ def visit_FuncDefNode(self, node):
         else:
             pf_cname = node.py_func.entry.func_cname
 
+        cname = node.entry.pyfunc_cname
+        if cname is None:
+            cname = node.entry.func_cname
+        # For functions defined using def, cname will be pyfunc_cname=__pyx_pf_*
+        # For functions defined using cpdef or cdef, cname will be func_cname=__pyx_f_*
+        # In all cases, cname will be the name of the function containing the actual code
```
Comment (scoder) [inline Cython/Compiler/ParseTreeTransforms.py:3474]:
```suggestion
        # For functions defined using def, cname will be pyfunc_cname=__pyx_pf_*
        # For functions defined using cpdef or cdef, cname will be func_cname=__pyx_f_*
        # In all cases, cname will be the name of the function containing the actual code
        cname = node.entry.pyfunc_cname or node.entry.func_cname
```

File: Cython/StringIOTree.py (hunk 13 above)
Comment (Volker-Weissmann) [reply Cython/StringIOTree.py]: Fixed that in the newest commit

File: docs/src/userguide/debugging.rst (hunk 14 above)
Comment (Volker-Weissmann) [reply docs/src/userguide/debugging.rst:24]: Interesting question. Even before this PR, we asked users to build their own gdb package using python2 (see lines 20-22 in debugging.rst).
I just tested it with the newest Cython version with my system supplied gdb that uses python3 and it works in dfab326da347a89a8941e9b1247aaa130e0e7ef0 . Do you know why we once told the user to use python2? If not, we can remove this part.

**Comment by scoder** [comment]
Thanks!
