### ISSUE TITLE
classmethod broken with Python 3.9

### ISSUE THREAD

**Issue by Synss** [cython/cython#3395]
# Steps to reproduce – MWE

```python
class Klass:
    @classmethod
    def factory(cls):
        return cls.other_factory()

    @classmethod
    def other_factory(cls):
        return cls()
```

save in ```.pyx``` and compile with cython (```build_ext -i```) in a Python 3.9 environment

```
Python 3.9.0a4 (default, Feb 29 2020, 15:47:57) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cm
>>> cm.Klass.factory()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cm.pyx", line 4, in cm.Klass.factory
    return cls.other_factory()
AttributeError: type object 'type' has no attribute 'other_factory'
>>> 
```

# Observed behavior

The ```classmethod``` decorator seems to return ```cls = type(type(self))``` instead of ```cls = type(self)``` and fails.

# Expected behavior

```Klass.factory()``` calls ```Klass.other_factory()``` and returns a ```Klass``` instance.

# Note

* The same code, compiled with the same cython version, works fine with python 2.7 or 3.4-3.8.
* Bug reproduced with the latest cython release from the cheese shop and GitHub master.

# See Also:

This could be related to https://github.com/cython/cython/issues/3349, although as far as I understand, the poster there says that the ```classmethod``` tests now pass.

**Comment by da-woods** [comment]
It works for me on master but not on 0.29.15. Are you sure you're forcing the rebuilding of the Cython file between changing versions?

**Comment by Synss** [comment]
I double checked with a clean venv and cython from master and yes, you are correct, it works. I must have had a polluted venv somehow.

Thank you, I'll wait for the next release.
