### ISSUE TITLE
[BUG] 3.0.0.rc2 PyInterpreterState_GetID undefined symbol pypy 3.9

### ISSUE THREAD

**Issue by illume** [cython/cython#5529]
### Describe the bug

pygame doesn't compile with pypy 3.9 when using cython 3.0.0.rc2

```
  src_c/_sdl2/sdl2.c:2933:29: warning: implicit declaration of function ‘PyInterpreterState_GetID’; did you mean ‘PyInterpreterState_Next’? [-Wimplicit-function-declaration]
     2933 |     PY_INT64_T current_id = PyInterpreterState_GetID(PyThreadState_Get()->interp);
          |                             ^~~~~~~~~~~~~~~~~~~~~~~~
          |                             PyInterpreterState_Next


ImportError: /tmp/tmp.gCm2VEnAmb/venv/lib/pypy3.9/site-packages/pygame/_sdl2/sdl2.pypy39-pp73-x86_64-linux-gnu.so: 
undefined symbol: PyInterpreterState_GetID
```

### Code to reproduce the behaviour:

See this PR https://github.com/pygame/pygame/pull/3957

```bash
git clone https://github.com/pygame/pygame.git
cd pygame
git checkout cython-updates
python -m pip install .
```

### Expected behaviour

It compiles.

### OS

manylinux

### Python version

pypy 3.9

### Cython version

3.0.0.rc2

**Comment by mattip** [comment]
This is not a problem with Cython. The build is using an older version of PyPy3.9. I will comment on the pygame issue, but I think this should be closed here.

**Comment by illume** [comment]
Ok, thanks for the info!

**Comment by ttencate** [comment]
> Edit: see also https://foss.heptapod.net/pypy/pypy/-/issues/3955

Link is dead, see https://github.com/pypy/pypy/issues/3733 and https://github.com/pypy/pypy/issues/3950. TL;DR: fixed in pypy 7.3.10.
