### ISSUE TITLE
Build errors after upgrading to 0.28 from 0.27.3

### ISSUE THREAD

**Issue by ilayn** [cython/cython#2154]
On SciPy, we have started to see test errors specific to a Cythonized function and the error is a generic 

    AttributeError: 'cython_function_or_method' object has no attribute '__func__'

The relevant offending line is at 
https://github.com/scipy/scipy/blob/master/scipy/spatial/qhull.pyx#L2161 and also line 1869 of the same file is the definition of `Delaunay.add_point` . 

and also an example of the CI fails is 

https://ci.appveyor.com/project/scipy/scipy/build/1.0.2241/job/8w577h0f6me8kfdj?fullLog=true#L8324

Is this an expected issue due to a new change or a known issue?

**Comment by scoder** [comment]
This is most likely due to #2105. Could you try it without the `__func__`?

**Comment by oleksandr-pavlyk** [comment]
@scoder Yes, removing `__func__` does resolve the failure.
