### ISSUE TITLE
[BUG] listobject.h:33:36: error: void value not ignored as it ought to be

### ISSUE THREAD

**Issue by AlexLuya** [cython/cython#4873]
Bug report
When running a "python3 setup install",I got an error:

/usr/include/python3.10/cpython/listobject.h:33:36: error: void value not ignored as it ought to be
   33 | #define PyList_SET_ITEM(op, i, v) ((void)(_PyList_CAST(op)->ob_item[i] = (v)))
      |                                   ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Cursor.c:1088:13: note: in expansion of macro ‘PyList_SET_ITEM’
Your environment

CPython versions tested on: 0.29.28
Operating system and architecture: ubuntu 22.04 x86_64

**Comment by da-woods** [comment]
> When running a "python3 setup install",I got an error:

What are you trying to install?

**Comment by da-woods** [comment]
https://github.com/python/cpython/issues/94507#issuecomment-1173024670

> Remember to include enough code to actually reproduce the bug.

I thought it *might* be a Cython issue because 0.29.28 is a Cython version. I'm less convinced now. It looks like it was some invalid hand-written Python code that was broken by https://github.com/python/cpython/pull/19975.

**Comment by da-woods** [comment]
I'll reopen this if/when you can provide details of how Cython is involved

**Comment by AlexLuya** [comment]
> > When running a "python3 setup install",I got an error:
> 
> What are you trying to install?

Compilation error looks like this:

![Workspace 1_1455](https://user-images.githubusercontent.com/303353/177259791-405924e0-b64f-4686-8caa-02f11c78cc6d.png)

corresponded code is:

```
static 
sdint2
Cursor_SetColVariables(
    udt_Cursor*     self
)
{
    udint2          icol;
    udt_Variable*   udt_var;

    if ((int)self->arraySize < 0 || self->arraySize > ULENGTH_MAX)
    {
        PyErr_SetString(g_ErrorException, "Invalid cursor arraysize\n");
        return -1;
    }

    Py_CLEAR(self->col_variables);

    self->col_variables = PyList_New(self->colCount);
    if (self->col_variables == NULL)
    {
        if (!PyErr_Occurred())
            PyErr_NoMemory();

        return -1;
    }

    for (icol = 0; icol < self->colCount; icol ++)
    {
        udt_var = Variable_Define(self, self->hdesc_col, icol + 1, (udint4)self->arraySize);
        if (udt_var == NULL)
            return -1;

        if (PyList_SET_ITEM(self->col_variables, icol, (PyObject*)udt_var) < 0)//-------------------------------this line caused problem
            return -1;
    }

    self->org_bindArraySize = self->bindArraySize;

    return 0;
}

and completed code is attached.

```
[Cursor.txt](https://github.com/cython/cython/files/9043679/Cursor.txt)

**Comment by AlexLuya** [comment]
> I'll reopen this if/when you can provide details of how Cython is involved

Hello,details has been provided

**Comment by da-woods** [comment]
This definitely isn't Cython-generated code so it isn't a Cython bug.
