### ISSUE TITLE
[BUG] Can't import module build  from pyx file in Apple Silicon

### ISSUE THREAD

**Issue by ipconfiger** [cython/cython#4018]
**Describe the bug**
Can not import module build from pyx file in Apple Silicon

Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/3.9.1/bin/encpy", line 33, in <module>
    sys.exit(load_entry_point('encrypedloader==0.0.36', 'console_scripts', 'encpy')())
  File "/Users/alex/.pyenv/versions/3.9.1/bin/encpy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/site-packages/encrypedloader-0.0.36-py3.9-macosx-11.1-arm64.egg/encrypedloader/__init__.py", line 2, in <module>
ImportError: cannot import name 'install' from 'encrypedloader.loader' (/Users/alex/Library/Caches/Python-Eggs/encrypedloader-0.0.36-py3.9-macosx-11.1-arm64.egg-tmp/encrypedloader/loader.cpython-39-darwin.so)

but it's work fine in aother linux pc(ubuntu20.04)

**To Reproduce**
Code to reproduce the behaviour:
```python

     cmdclass={'build_ext': build_ext},
     ext_modules=cythonize("encrypedloader/loader.pyx", language_level="3"),

```

**Expected behavior**
can import modules from .so file

**Environment (please complete the following information):**
 - OS: [e.g. Linux, Windows, macOS]
 - Python version [e.g. 3.9.1]
 - Cython version [e.g. 0.29.18]

**Additional context**

**Comment by robertwb** [comment]
Looks like you're using a custom build_ext with `cmdclass={'build_ext': build_ext}`. Also, given the symptoms, this is likely a setuptools/C compile issue, not a Cython one.
