### ISSUE TITLE
[BUG] 3.3.0: breaks lap 0.5.13: error: 'isfinite' was not declared in this scope; did you mean 'std::isfinite'?

### ISSUE THREAD

**Issue by 0-wiz-0** [cython/cython#7915]
### Describe the bug

After updating cython in pkgsrc to 3.3.0, the build of lap 0.5.13 started failing with:
```
building 'lap._lapjv' extension
c++ -O2 -g -fstack-clash-protection -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -g -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -fPIC -I_lapjv_cpp -I/usr/pkg/lib/python3.14/site-packages/numpy/_core/include -Ilap -I/usr/pkg/include/python3.14 -c _lapjv_cpp/_lapjv.cpp -o build/temp.netbsd-11.99.7-amd64-cpython-314/_lapjv_cpp/_lapjv.o
_lapjv_cpp/_lapjv.cpp: In function 'int __Pyx_PyObject_CompareFloatIntBoolLt(PyObject*, PyObject*)':
_lapjv_cpp/_lapjv.cpp:12251:19: error: 'isfinite' was not declared in this scope; did you mean 'std::isfinite'?
12251 |     if (unlikely(!isfinite(float_op1))) {
      |                   ^~~~~~~~
_lapjv_cpp/_lapjv.cpp:1504:43: note: in definition of macro 'unlikely'
 1504 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
In file included from /usr/include/g++/complex:44,
                 from _lapjv_cpp/_lapjv.cpp:1544:
/usr/include/g++/cmath:1142:5: note: 'std::isfinite' declared here
 1142 |     isfinite(_Tp)
      |     ^~~~~~~~
error: Command '['c++', '-O2', '-g', '-fstack-clash-protection', '-I/usr/pkg/include', '-I/usr/include', '-I/usr/pkg/include/python3.14', '-g', '-I/usr/pkg/include', '-I/usr/include', '-I/usr/pkg/include/python3.14', '-fPIC', '-I_lapjv_cpp', '-I/usr/pkg/lib/python3.14/site-packages/numpy/_core/include', '-Ilap', '-I/usr/pkg/include/python3.14', '-c', '_lapjv_cpp/_lapjv.cpp', '-o', 'build/temp.netbsd-11.99.7-amd64-cpython-314/_lapjv_cpp/_lapjv.o']' returned non-zero exit status 1.
```

### Code to reproduce the behaviour:

Try building the 0.5.13 release of https://github.com/gatagat/lap using the pypi distfile.

### Expected behaviour

Build succeeds.

### OS

NetBSD

### Python version

3.14.7

### Cython version

3.3.0

**Comment by 0-wiz-0** [comment]
This also breaks [scipy](https://releng.netbsd.org/pkgreports/shadow/HEAD/NetBSD-11.0-x86_64/20260824.0842/py313-scipy-1.18.0/build.log) and [renpy](https://releng.netbsd.org/pkgreports/shadow/HEAD/NetBSD-11.0-x86_64/20260824.0842/py312-renpy-8.5.3/build.log).

**Comment by scoder** [comment]
For future reference, the issue in NetBSD is being discussed here:
https://mail-index.netbsd.org/tech-toolchain/2026/08/25/msg004887.html
