### ISSUE TITLE
C extension does not build on Python 3.8.0a4

### ISSUE THREAD

**Issue by nitzmahone** [cython/cython#2960]
Build output:
```
 ext/_yaml.c:24767:34: error: too few arguments to function call, expected 16, have 15
    __pyx_codeobj__41 = (PyObject*)__Pyx_PyCode_New(0, 0, 1, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__40, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_ext__yaml_pyx, __pyx_n_s_get_version_string, 4, __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__41)) __PYX_ERR(0, 4, __pyx_L1_error)
```

This is apparently related to a Cython bug, which has a backport in-flight for Cython 0.29: https://github.com/cython/cython/issues/2938 - once that's been released, we should just need to ship a new pyyaml release with the Cython output from a fixed version of Cython.
