### PR TITLE
Avoid Py_UNICODE deprecation warning for arrayarray

### LINKED ISSUE #6607: [BUG] Error C4996: 'Py_UNICODE': deprecated in 3.13 - on cp313-win32.
### Describe the bug

I have a Cython project that errors with error C4996: 'Py_UNICODE': deprecated in 3.13 only when building on Python 3.13 on win32. The same code builds with Python 3.13 on Windows with amd64 and on ubunto-latest and macos-latest. 

The project does not explicitly use Py_UNICODE but does use array.array('B') and I see [from ](url)https://github.com/cython/cython/issues/5982#issuecomment-1955195289 there may be connection. 

Error:
https://github.com/microsoft/VisualTrueType/actions/runs/12700069355/job/35402026392

Thanks

### Code to reproduce the behaviour:

```cython
# example code
```

### Expected behaviour

_No response_

### OS

Windows win32. 

### Python version

Python 3.13

### Cython version

current

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by da-woods**
Change the helper union for arrayarray so that users who don't use as_pyunicodes don't get a deprecation warning. However, add our own deprecation warning for anyone that does use it.

Fixes #6607

### CODE REVIEW

**Comment by rodrigc** [comment]
I think this patch would be useful to eliminate this warning I saw when building https://github.com/apache/pyiceberg with Python 3.13:

```
pyiceberg/avro/decoder_fast.c:2243:9: warning: 'Py_UNICODE' is deprecated [-Wdeprecated-declarations]
 2243 |         Py_UNICODE *as_pyunicodes;
      |         ^
/usr/local/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/unicodeobject.h:10:1: note: 'Py_UNICODE' has been explicitly marked deprecated here
   10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
      | ^
/usr/local/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13/pyport.h:251:54: note: expanded from macro 'Py_DEPRECATED'
  251 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
      |                        
```
