### ISSUE TITLE
[BUG] deleted copy constructor mistakenly invoked with Cython 3.x (but worked with Cython 0.29.x)

### ISSUE THREAD

**Issue by leofang** [cython/cython#6228]
### Describe the bug

The deleted copy constructor is mistakenly invoked with the 3.x series, leading to the following g++ error (Cython does not raise):
```bash
$ cythonize -i -3 test_cython_move.pyx
Compiling /home/leof/dev/python/temp/test_cython_move.pyx because it changed.
[1/1] Cythonizing /home/leof/dev/python/temp/test_cython_move.pyx
/home/leof/dev/python/temp/test_cython_move.cpp: In function ‘PyObject* __pyx_pf_16test_cython_move_f(PyObject*)’:
/home/leof/dev/python/temp/test_cython_move.cpp:3189:76: error: use of deleted function ‘my_obj<T>::my_obj(const my_obj<T>&) [with T = std::vector<long int>]’
 3189 |   __pyx_v_m = __PYX_STD_MOVE_IF_SUPPORTED(((my_obj<std::vector<int64_t> > )__pyx_t_2));
      |                                                                            ^~~~~~~~~
/home/leof/dev/python/temp/test_cython_move.cpp:1859:52: note: in definition of macro ‘__PYX_STD_MOVE_IF_SUPPORTED’
 1859 |   #define __PYX_STD_MOVE_IF_SUPPORTED(x) std::move(x)
      |                                                    ^
/home/leof/dev/python/temp/test_cython_move.cpp:1299:9: note: declared here
 1299 |         my_obj(const my_obj&) = delete;
      |         ^~~~~~
error: command '/usr/bin/gcc' failed with exit code 1
```

I see the line in the `f()` function gets compiled to 
- Cython 0.29.x:
```c++
  __pyx_v_m = ((my_obj<std::vector<int64_t> > )__pyx_fuse_2__pyx_f_16test_cython_move_get_resource_holder(__pyx_t_1, ((int64_t *)NULL)));
```
- Cython 3.x:
```c++
__pyx_v_m = __PYX_STD_MOVE_IF_SUPPORTED(((my_obj<std::vector<int64_t> > )__pyx_t_2));
```
Maybe the night is late and I am not thinking straight, so I could be wrong, but I feel the code generated by 0.29.x makes better sense (invoking move assignment).

### Code to reproduce the behaviour:

```cython
# distutils: language = c++

cimport cpython
from libc.stdint cimport int32_t, int64_t, intptr_t
from libcpp.vector cimport vector
from libcpp cimport bool as cppbool
from libcpp cimport nullptr_t, nullptr
from libcpp.memory cimport unique_ptr
from libcpp.utility cimport move
from cython.operator cimport dereference as deref


cdef extern from * nogil:
    """
    template<typename T>
    class my_obj {
      public:
        my_obj() noexcept = default;

        explicit my_obj(T data): data_(data)
        {
        }

        my_obj(const my_obj&) = delete;

        my_obj& operator=(const my_obj&) = delete;

        my_obj(my_obj&& other) noexcept
        {
            data_ = other.data_;
        }

        my_obj& operator=(my_obj&& other) noexcept
        {
            data_ = other.data_;
            return *this;
        }

        ~my_obj() = default;

        void swap(my_obj& other) noexcept
        {
            std::swap(data_, other.data_);
        }

        T get() const noexcept
        {
            return data_;
        }

      private:
        T data_;
    };
    """
    # xref: cython/Cython/Includes/libcpp/memory.pxd
    cdef cppclass my_obj[T]:
        my_obj()
        my_obj(T)
        my_obj(my_obj[T]&)

        # Modifiers
        void swap(my_obj&)

        # Observers
        T get()


ctypedef fused ResT:
    int
    int32_t
    int64_t


cdef my_obj[ vector[ResT] ] get_resource_holder(object obj, ResT* __unused):
    cdef my_obj[ vector[ResT] ] holder
    cdef vector[ResT]* vec
    if cpython.PySequence_Check(obj):
        vec = new vector[ResT](len(obj))
        for i in range(len(obj)):
            deref(vec)[i] = obj[i]
    else:
        raise RuntimeError
    return move(holder)


def f():
    cdef my_obj[ vector[int64_t] ] m = get_resource_holder[int64_t]([1,2,3], <int64_t*>NULL)
```

### Expected behaviour

Works in both 0.29.x and 3.x.

### OS

Linux

### Python version

3.11.3

### Cython version

0.29.37 / 3.0.10

### Additional context

Any workaround to unblock us is also appreciated 🙏

**Comment by da-woods** [comment]
It's related to https://github.com/cython/cython/issues/6225 in that it shouldn't put move round a cast (but I don't know why it's generating the cast in the first place).

The difference between 0.29.x and 3.0.x is that it goes via a temp in 3.0.x. This is because `cdef` functions can raise exceptions by default. If you mark `get_resource_holder` as `noexcept` it'll go back to the old code.

**Comment by leofang** [comment]
Thanks, @da-woods! Adding `noexcept` works! Yeah I dunno why a cast is generated either, doesn't seem to be necessary (since by design the type of a temp is guaranteed to be the same) and gcc is not smart enough to eliminate the cast op.

btw the ugliness of `get_resource_holder` (having an `__unused` argument of type `ResT*`) was to work around the limitation of using fused types with C++ templates (#5544) 😅

**Comment by ksimpson-work** [comment]
@da-woods I have looked into this and found the root cause of the erroneous cast to be CTypedefType.__get_attr_ returning a bound method, bound to a different self than the caller expects. 

cc @leofang 

[https://github.com/cython/cython/blob/cec7ac08bb0a59d7371bb9316c3209d81ca28d02/Cython/Compiler/PyrexTypes.py#L616-L617](url)

In this case, the caller calls lhs.is_same_as_resolved_type(), and what happens in reality is lhs.base_type.is_same_as_resolved_type(rhs). I'm not sure about all the implications of a fix to this would be, but I think a simple patch to fix the behavior of is_same_as_resolved_type, would be for CTypedefType to implement it as lhs.base_type.is_same_as_resolved_type(rhs.base_type).
