### ISSUE TITLE
python 3.5.3 build failure with cython 0.27

### ISSUE THREAD

**Issue by sonots** [cython/cython#1885]
https://travis-ci.org/cupy/cupy/jobs/279366697

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ugczwovl/fastrlock-0.3/setup.py", line 117, in <module>
  File "/opt/python/3.5.3/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.5.3/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.5.3/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/opt/python/3.5.3/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python/3.5.3/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/python/3.5.3/lib/python3.5/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/python/3.5.3/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python/3.5.3/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/opt/python/3.5.3/lib/python3.5/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py", line 192, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py", line 203, in cython_sources
    from Cython.Compiler.Main \
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
  File "Cython/Compiler/Scanning.py", line 54, in init Cython.Compiler.Scanning
AttributeError: type object 'Cython.Compiler.Scanning.Method' has no attribute '__reduce_cython__'
```

It worked before with cython 0.26.1.
Also, cython 0.27 works with python 3.4.6.

**Comment by scoder** [comment]
Look at the file paths in the traceback. You seem to have a local copy of Cython, which leads to the Scanning module being imported as uncompiled Python module.

**Comment by scoder** [comment]
Hmm, or maybe not. Let me investigate a little.

**Comment by scoder** [comment]
Still no idea what might trigger this. Also, it's unclear why it should call `setup.py` in `fastrlock`, when there is a wheel that it can just unpack. That `setup.py` file then says `building without Cython`, but then apparently setuptools calls into Cython anyway, for no good reason.

However, since this is pickling related code, and there is no reason why the failing class should ever get pickled, I've disabled pickling support for some modules. That should also resolve this issue.
https://github.com/cython/cython/commit/8e6bbf4033295e34e2b64ac4d267623148d383a7

**Comment by sonots** [comment]
thanks, current master seems working fine :)
