### PR TITLE
Add includes for `isfinite` in float comparison code

### LINKED ISSUE #7915: [BUG] 3.3.0: breaks lap 0.5.13: error: 'isfinite' was not declared in this scope; did you mean 'std::isfinite'?
### Describe the bug

After updating cython in pkgsrc to 3.3.0, the build of lap 0.5.13 started failing with:
```
building 'lap._lapjv' extension
c++ -O2 -g -fstack-clash-protection -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -g -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -fPIC -I_lapjv_cpp -I/usr/pkg/lib/python3.14/site-packages/numpy/_core/include -Ilap -I/usr/pkg/include/python3.14 -c _lapjv_cpp/_lapjv.cpp -o build/temp.netbsd-11.99.7-amd64-cpython-314/_lapjv_cpp/_lapjv.o
_lapjv_cpp/_lapjv.cpp: In function 'int __Pyx_PyObject_CompareFloatIntBoolLt(PyObject*, PyObject*)':
_lapjv_cpp/_lapjv.cpp:12251:19: error: 'isfinite' was not declared in this scope; did you mean 'std::isfinite'?
12251 |     if (unlikely(!isfinite(float_op1))) {
      |                   ^~~~~~~~
_lapjv_cpp/_lapjv.cpp:1504:43: note: in definition of macro 'unlikely'
 1504 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
In file included from /usr/include/g++/complex:44,
                 from _lapjv_cpp/_lapjv.cpp:1544:
/usr/include/g++/cmath:1142:5: note: 'std::isfinite' declared here
 1142 |     isfinite(_Tp)
      |     ^~~~~~~~
error: Command '['c++', '-O2', '-g', '-fstack-clash-protection', '-I/usr/pkg/include', '-I/usr/include', '-I/usr/pkg/include/python3.14', '-g', '-I/usr/pkg/include', '-I/usr/include', '-I/usr/pkg/include/python3.14', '-fPIC', '-I_lapjv_cpp', '-I/usr/pkg/lib/python3.14/site-packages/numpy/_core/include', '-Ilap', '-I/usr/pkg/include/python3.14', '-c', '_lapjv_cpp/_lapjv.cpp', '-o', 'build/temp.netbsd-11.99.7-amd64-cpython-314/_lapjv_cpp/_lapjv.o']' returned non-zero exit status 1.
```

### Code to reproduce the behaviour:

Try building the 0.5.13 release of https://github.com/gatagat/lap using the pypi distfile.

### Expected behaviour

Build succeeds.

### OS

NetBSD

### Python version

3.14.7

### Cython version

3.3.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by da-woods**
Fixes #7915.

Arguably they could be declarated once further, but I think it's easiest to reason about if they're in the same tempita `if` as the place that they're used (and include guards should keep it fairly cheep).

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
Thanks for the patch.
I've tried it, byt it doesn't solve the problem for me:
```
c++ -O2 -g -fstack-clash-protection -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -g -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -fPIC -I_lapjv_cpp -I/usr/pkg/lib/python3.14/site-packages/numpy/_core/include -Ilap -I/usr/pkg/include/python3.14 -c _lapjv_cpp/_lapjv.cpp -o build/temp.netbsd-11.99.7-amd64-cpython-314/_lapjv_cpp/_lapjv.o
_lapjv_cpp/_lapjv.cpp: In function 'int __Pyx_PyObject_CompareFloatIntBoolLt(PyObject*, PyObject*)':
_lapjv_cpp/_lapjv.cpp:12252:19: error: 'isfinite' was not declared in this scope; did you mean 'std::isfinite'?
12252 |     if (unlikely(!isfinite(float_op1))) {
      |                   ^~~~~~~~
_lapjv_cpp/_lapjv.cpp:1504:43: note: in definition of macro 'unlikely'
 1504 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
In file included from /usr/include/g++/complex:44,
                 from _lapjv_cpp/_lapjv.cpp:1544:
/usr/include/g++/cmath:1142:5: note: 'std::isfinite' declared here
 1142 |     isfinite(_Tp)
      |     ^~~~~~~~
error: Command '['c++', '-O2', '-g', '-fstack-clash-protection', '-I/usr/pkg/include', '-I/usr/include', '-I/usr/pkg/include/python3.14', '-g', '-I/usr/pkg/include', '-I/usr/include', '-I/usr/pkg/include/python3.14', '-fPIC', '-I_lapjv_cpp', '-I/usr/pkg/lib/python3.14/site-packages/numpy/_core/include', '-Ilap', '-I/usr/pkg/include/python3.14', '-c', '_lapjv_cpp/_lapjv.cpp', '-o', 'build/temp.netbsd-11.99.7-amd64-cpython-314/_lapjv_cpp/_lapjv.o']' returned non-zero exit status 1.

```
even though the new include seems to be in the right place - from lap's file:
```
/* PyObjectCompare */
#ifndef __Pyx_DEFINED_PyObject_CompareFloatIntBoolLt
#define __Pyx_DEFINED_PyObject_CompareFloatIntBoolLt
#include <math.h>
static int __Pyx_PyObject_CompareFloatIntBoolLt(PyObject *op1, PyObject *op2) {
    double float_op1 = __Pyx_PyFloat_AS_DOUBLE(op1);
    #if !CYTHON_ASSUME_SAFE_MACROS
    if (unlikely(float_op1 == -1. && PyErr_Occurred())) return -1;
    #endif
    #if CYTHON_USE_PYLONG_INTERNALS
    if (__Pyx_PyLong_IsCompact(op2)) {
        Py_ssize_t iop2 = __Pyx_PyLong_CompactValue(op2);
        if (float_op1 < ((double)iop2)) goto __pyx_return_true; else goto __pyx_return_false;
    }
    if (unlikely(!isfinite(float_op1))) {
        if (float_op1 < 0.0) goto __pyx_return_true; else goto __pyx_return_false;
    } else {
        int sign2 = __Pyx_PyLong_Sign(op2);
        if (float_op1 >= 0.) {
            if (sign2 < 0) goto __pyx_return_false;
            if (float_op1 < (double) (1L << PyLong_SHIFT)) goto __pyx_return_true;
        } else {
            if (sign2 > 0) goto __pyx_return_true;
            if (float_op1 > -(double) (1L << PyLong_SHIFT)) goto __pyx_return_false;
        }
    }
    #else
    if (unlikely(!isfinite(float_op1))) {
        if (float_op1 < 0.0) goto __pyx_return_true; else goto __pyx_return_false;
    } else {
        int overflow2;
        long iop2 = PyLong_AsLongAndOverflow(op2, &overflow2);
        if (likely(!overflow2)) {
            if ((long long) iop2 >= (1LL << 53)) {
                overflow2 = 1;
            } else if ((long long) iop2 <= - (1LL << 53)) {
                overflow2 = -1;
            } else {
                if (float_op1 < ((double) iop2)) goto __pyx_return_true; else goto __pyx_return_false;
            }
        }
        if (overflow2 > 0) {
            if (float_op1 < ((double) (1LL << 53))) goto __pyx_return_true;
        } else {
            if (float_op1 > - ((double) (1LL << 53))) goto __pyx_return_false;
        }
    }
    #endif
    return __Pyx_PyObject_RichCompareBool(op1, op2, Py_LT);
__pyx_return_true:
    return 1;
__pyx_return_false:
    return 0;
}
#endif
```
I'm using gcc 14.3.0 (default) on NetBSD 11.99.7 in case it matters.

**Comment by da-woods** [comment]
Hmmmm. math.h is already in Python.h so actually we shouldn't need this.

It's a C99 function? I don't know if that makes any difference. I think we (and Python) broadly require C99 but that doesn't mean everyone implements it fully.

**Comment by da-woods** [comment]
I'll close this though because it isn't the fix

**Comment by da-woods** [comment]
> It's a C99 function?

Does it work if you use `-std=c99` as a C flag?

**Comment by 0-wiz-0** [comment]
Well, it's c++ code and calling the c++ compiler:
```
c++ -O2 -g -fstack-clash-protection -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -g -I/usr/pkg/include -I/usr/include -I/usr/pkg/include/python3.14 -fPIC -I_lapjv_cpp -I/usr/pkg/lib/python3.14/site-packages/numpy/_core/include -Ilap -I/usr/pkg/include/python3.14 -c _lapjv_cpp/_lapjv.cpp -o build/temp.netbsd-11.99.7-amd64-cpython-314/_lapjv_cpp/_lapjv.o
```
so I don't think choosing a C standard makes sense.

**Comment by da-woods** [comment]
Good point. Normally the C functions would be available in C++ I believe, although I'm not sure exactly what C standards are available in each c++ standard. I'll investigate a bit more later.

But you're right - specifying a c standard isn't sensible here

**Comment by 0-wiz-0** [comment]
I played around a bit - on godbolt.org a simple test using `isfinite` works as long as `math.h` is included, doesn't matter if `cmath` is included or not.
However, on NetBSD, including `cmath` breaks a simple `isfinite` and only `std::isfinite` is accepted once it is included.

Could you please come up with a patch that uses `std::isfinite` instead of `isfinite`? That should work on all systems.

**Comment by scoder** [comment]
`std::isfinite(float)` is old but `std::isfinite(double)` requires C++11 according to https://en.cppreference.com/cpp/numeric/math/isfinite
It's probably still fine in practice, I think we mostly target C++11 anyway.
I'll create a PR.

**Comment by scoder** [comment]
Superseded by https://github.com/cython/cython/pull/7930
