### ISSUE TITLE
[BUG] Error C4996: 'Py_UNICODE': deprecated in 3.13 - on cp313-win32. 

### ISSUE THREAD

**Issue by paullinnerud** [cython/cython#6607]
### Describe the bug

I have a Cython project that errors with error C4996: 'Py_UNICODE': deprecated in 3.13 only when building on Python 3.13 on win32. The same code builds with Python 3.13 on Windows with amd64 and on ubunto-latest and macos-latest. 

The project does not explicitly use Py_UNICODE but does use array.array('B') and I see [from ](url)https://github.com/cython/cython/issues/5982#issuecomment-1955195289 there may be connection. 

Error:
https://github.com/microsoft/VisualTrueType/actions/runs/12700069355/job/35402026392

Thanks

### Code to reproduce the behaviour:

```cython
# example code
```

### OS

Windows win32. 

### Python version

Python 3.13

### Cython version

current

**Comment by da-woods** [comment]
You're right that this is coming from `array.array` and you're right that it's deprecated but not yet removed.

This is unfortunately the only remaining case where we need to use `Py_UNICODE` in code where the user hasn't specifically asked for it.

The fact this is an error instead of a warning is self-inflicted though - you look to be passing this argument to MSVC: https://learn.microsoft.com/en-us/cpp/build/reference/sdl-enable-additional-security-checks?view=msvc-170. Unfortunately I don't know how you get the run-time benefits of that feature without the warnings-as-errors.

**Comment by da-woods** [comment]
It should be possible to fix this in a future version I think

**Comment by paullinnerud** [comment]
Thanks I'll look into modifying the sdl argument until it's fixed.
