### PR TITLE
Support weakref in limited api cdef classes

### LINKED ISSUE #5793: [BUG] classes with `__weakref__` don't compile using the limited api
### Describe the bug

Hello everyone,

I was trying to compile a class with a `cdef object __weakref__` attribute in the limited api and it crashes with:

```
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -DCYTHON_LIMITED_API=1 -DPy_LIMITED_API=0x030B0000 -I/private/var/folders/l4/gpyzwv455hzbmbv78x05555h0000gn/T/build-env-x8r7d7re/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c limited_weakref.cpp -o build/temp.macosx-14-arm64-cpython-311/limited_weakref.o
limited_weakref.cpp:3707:38: error: member access into incomplete type 'PyTypeObject' (aka '_typeobject')
  if (__pyx_ptype_15limited_weakref_A->tp_weaklistoffset == 0) __pyx_ptype_15limited_weakref_A->tp_weaklistoffset = offsetof(struct __pyx_obj_15limited_weakref_A, __weakref__);
                                     ^
/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:20:16: note: forward declaration of '_typeobject'
typedef struct _typeobject PyTypeObject;
               ^
limited_weakref.cpp:3707:95: error: member access into incomplete type 'PyTypeObject' (aka '_typeobject')
  if (__pyx_ptype_15limited_weakref_A->tp_weaklistoffset == 0) __pyx_ptype_15limited_weakref_A->tp_weaklistoffset = offsetof(struct __pyx_obj_15limited_weakref_A, __weakref__);
                                                                                              ^
/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:20:16: note: forward declaration of '_typeobject'
typedef struct _typeobject PyTypeObject;
               ^
2 errors generated.
error: command '/usr/bin/clang' failed with exit code 1
```

-Andreas

### Code to reproduce the behaviour:

```cython
# limited_weakref.pyx

cdef class A:
    cdef object __weakref__
```

### Expected behaviour

It should compile.

### OS

_No response_

### Python version

_No response_

### Cython version

_No response_

### Additional context

The relevant compiler code seems to be here: https://github.com/cython/cython/blob/bc32b7ec3f15f532c0ae59b930544c23172e8c50/Cython/Compiler/Nodes.py#L5817-L5831

### PR DESCRIPTION
**Pull request by da-woods**
Fixes #5793.

Note that this won't work on Python versions <3.9. (The code will compile fine, but the classes won't be weak referenceable).

### CODE REVIEW

**Comment by scoder** [comment]
>Note that this won&#39;t work on Python versions &lt;3.9. (The code will compile fine, but the classes won&#39;t be weak referenceable).

We could print a C compiler warning when we detect that case. That would make the problem visible. It's then best for users to either require a newer Python version or work around the missing feature at runtime. We shouldn't fail the compilation for this.

**Comment by da-woods** [comment]
This is next on my list of limited API stuff that I'm threatening to merge fairly soon unless there are objections.
